### ISSUE TITLE
[feature request] поддержка ctrl-v в беседы картинок из буфера обмена в firefox

### ISSUE THREAD

**Issue by peczony** [VkOpt/VkOpt#140]
Вконтакте уже достаточно давно запилили следующую фичу: если в беседе из-под хромиума нажать ctrl-v, можно скопировать картинку из буфера обмена. Firefox же они демонстративно игнорируют, хотя техническая возможность вставить картинку из буфера в Firefox тоже есть ([пруф](http://imgur.com/tools))

Можно ли было бы при помощи расширения имитировать поведение хромиума так, чтобы картинки вставлялись? (если что, понятия не имею о технической возможности/невозможности этого)

**Comment by KiberInfinity** [comment]
Не совсем раскопал как реализовано в Firefox у imgur.com, но по факту в событии "paste" у фаерфокса отсутствуют данные об изображении в данных этого события.
Но фаерфокс в contenteditable элементы вставляет изображение из буфера как <img src="data:image/png;base64...">. Можно вклинится в либу вк, которая удаляет мусор из поля ввода и до удаления выдрать этот base64 картинки, перегнать в Blob и залить примерно так:
<pre>
var binary = atob(base64image)
var array = new Uint8Array(binary.length)
for( var i = 0; i < binary.length; i++ ) { array[i] = binary.charCodeAt(i) }
blob = new Blob([array]);
blob.name = blob.filename = 'upload_' + new Date().toISOString() + '.png';
Upload.onFileApiSend(cur.imUploadInd, [blob]);
</pre>

**Comment by peczony** [comment]
Да, все, кто пишут про имплементацию Paste в FF, говорят про base64. А хромиум разве как-то иначе делает?

**Comment by KiberInfinity** [comment]
да. там в событии о вставке приходит тело скопированного изображения.

**Comment by Scvairy** [comment]
http://habrahabr.ru/company/cackle/blog/201190/
Вот это можно как-то адаптировать под вконтач?
Знал бы javascript, может быть и сам бы попытался, но, увы, я дно.

**Comment by RblSb** [comment]
О, давно хочу эту фичу, желательно не только в беседе. Буду рад помочь для скорейшей реализации, как можно связатс с разработчиками? :)

**Comment by Pmmlabs** [comment]
@RblSb форкай репозиторий, делай изменения, проверяй работоспособность и делай Pull Request.

**Comment by Scvairy** [comment]
![Ответ поддержки ВКонтакте](https://cloud.githubusercontent.com/assets/8327460/8953413/bb4484d0-35f7-11e5-81ca-ddb6b779134e.png)
Ну, ребят, я в вас верю!

**Comment by deltaidea** [comment]
[Вот тут](http://stackoverflow.com/q/21377838) есть объяснение, как это сделано у Imgur.

TL;DR:
Для Firefox:

- Ждём события `"paste"` у `document`.
- При событии фокусируемся на отдельном скрытом `<div contenteditable>`.
- Ждём, когда в DOM в этом `<div>` появятся дети. Пока вставка не завершится, детей не будет.
- Анализируем `innerHTML` этого `<div>`. Смотрим на вхождения строк:
  - `"<img ... src="` - это картинка,
  - `"base64,"` - в base64,
  - `"iVBORw0K"` - имеет индикатор PNG.
- Если все три подстроки есть, там точно `<img src="base64,..." alt="">`. С этим ясно как работать.

Дальше Imgur ещё пытается распарсить там `<a href="...">` и `<img src="...">` с обычными ссылками, но это уже по вкусу, я считаю.

**Comment by Pmmlabs** [comment]
Сделал плагин: #185 , его можно даже как юзерскрипт подключить, и будет работать на любой версии Vkopt

**Comment by peczony** [comment]
Тестирую, наблюдаю странное поведение. Если скопировать изображение в буфер в обычной десктопной программе (Irfanview, скажем, или просто принтскрин), вставка работает. Если скопировать картинку _в самом файрфоксе_, не работает.

**Comment by Pmmlabs** [comment]
Да, действительно, там вставляется картинка с оригинальным src, а не с base64. Надо найти функцию, которая загружает фотку по url. Я пока что нашел `cur.chooseMedia`, но там надо разобраться, как использовать. Ещё есть `checkURL`, но надо разобраться, как её вызывать.

**Comment by KiberInfinity** [comment]
> Надо найти функцию, которая загружает фотку по url

vk_media.js 
vk_photos.url(URL)
может тут что поможет.

**Comment by Pmmlabs** [comment]
@KiberInfinity эта функция предлагает выбрать альбом, куда сохранить загруженную фотографию. Я думаю, есть функция, которая сразу прикрепляет фото к сообщению.

**Comment by Pmmlabs** [comment]
а, ты в смысле, просто код посмотреть. да, наверное поможет. посмотрим.

**Comment by peczony** [comment]
Сегодня перестало работать (ощущение, что что-то поменялось на стороне контакта)

**Comment by Pmmlabs** [comment]
@peczony да, действительно перестало. На первый взгляд не нашел, в чем причина.
Если убрать из обработчиков события paste `Emoji.init/<()`, то работает, но лучше не убирать.

**Comment by Pmmlabs** [comment]
@peczony исправлено: #227

**Comment by peczony** [comment]
Спасибо, работает

**Comment by RblSb** [comment]
А с копированием картинок лисой и вставок в диалог никак? В текстовое поле такие пикчи успешно вставляются, но отправить их никак нельзя, вк как вложения их не прикрепляет.

**Comment by Pmmlabs** [comment]
Никак.
Копируй **адрес** картинки, а не саму картинку, тогда при вставке в поле ввода она сразу прикрепится.

**Comment by RblSb** [comment]
@Pmmlabs этот способ работает через раз, а иногда и через 10. Печально, ну ладн.

**Comment by Pmmlabs** [comment]
Через раз прикрепляются картинки при вставке url ? это уже какая-то локальная проблема, можно в поддержку ВК обратиться.
