### ISSUE TITLE
Валит все вкладки в firefox

### ISSUE THREAD

**Issue by Lucidyan** [VkOpt/VkOpt#142]
При открытии vk.com, с установленным расширением, все владки валятся с фаталом
Firefox 40.0a2 Developer Edition (Aurora)
Linux MS-7641 3.19.0-16-generic #16-Ubuntu  x86_64 x86_64 x86_64 GNU/Linux
Build identifier: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0

**Comment by Lucidyan** [comment]
Логи из консоли:
###!!! [MessageChannel][Child][/build/firefox-BDQUHa/firefox-40.0~a2~hg20150603r262503/ipc/glue/MessageChannel.cpp:800] Assertion (aMsg->priority() >= DispatchingSyncMessagePriority()) failed.  can't send sync message of a lesser priority than what's being dispatched 
  MessageChannel 'backtrace':
  [(0) out sync PContent::Msg_RpcMessage(actor=2147483647) ]
  [(1) out sync PStorage::Msg_Preload(actor=-5) ]
  remote Interrupt stack guess: 0
  deferred stack size: 0
  out-of-turn Interrupt replies stack size: 0
  Pending queue size: 0, front to back:
[Child 25461] ###!!! ABORT: can't send sync message of a lesser priority than what's being dispatched: file /build/firefox-BDQUHa/firefox-40.0~a2~hg20150603r262503/ipc/glue/MessageChannel.cpp, line 1883
[Child 25461] ###!!! ABORT: can't send sync message of a lesser priority than what's being dispatched: file /build/firefox-BDQUHa/firefox-40.0~a2~hg20150603r262503/ipc/glue/MessageChannel.cpp, line 1883

###!!! [Parent][MessageChannel::SendAndWait] Error: Channel error: cannot send/recv


###!!! [Parent][OnMaybeDequeueOne] Error: Channel error: cannot send/recv


###!!! [Parent][OnMaybeDequeueOne] Error: Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0x200076,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0x200076,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0x200076,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv


###!!! [Parent][MessageChannel] Error: (msgtype=0x200076,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv

**Comment by Pmmlabs** [comment]
это при включенном e10 что ли ?

**Comment by Lucidyan** [comment]
Да, при включенном - проблема, я так понял, известна? )

**Comment by Pmmlabs** [comment]
ага. Вкладки валятся в расширении на старой основе. Если собрать на основе Jetpack - то всё работает. Но там еще немного доработать надо, потому что есть некоторые проблемы. Обсуждаем здесь: #110

**Comment by Lucidyan** [comment]
Спасибо за оперативность!

**Comment by Pmmlabs** [comment]
пожалуйста. Если есть желание, можете помочь в решении проблем, описанных в той теме. Вы же Developer, раз юзаете Developer Edition ? ;)
