### ISSUE TITLE
Насчёт сохранения переписки

### ISSUE THREAD

**Issue by bodysome** [VkOpt/VkOpt#187]
**Для начала, хочу поблагодарить команду ВкОпт за этот плагин. Отличная вещь :)**

Но у меня есть пара вопросов насчёт сохранения переписки:

1. Почему все картинки сохраняются в виде прямых ссылок (видео и гифки не так сильно волнуют)? Из-за того, что сохраняется лишь один _html_ файл без папки с файлами (как при обычном сохранении страницы браузером)? Просто очень хочется _автономности_ сохранённой переписки.

2. Не сохраняются смайлики. Видимо из-за того, что прямые ссылки на смайлики _вне_ Контакта не работают. Если всё-таки у вас нет возможности сохранять все картинки в отдельную папку (как я писал выше), может хотя бы для смайликов стоит использовать _base64_? Или как-то задействовать [этот сайт] (http://www.emoji-cheat-sheet.com)?

`И не по теме: где сохраняются настройки ВкОпт при использовании онлайн хранилища настроек?`

**Comment by Pmmlabs** [comment]
В принципе, можно загнать всё в base64, я так сделал для [функции массового скачивания wiki-страниц](/VkOpt/VkOpt/pull/149)

> И не по теме: где сохраняются настройки ВкОпт при использовании онлайн хранилища настроек?

На серверах Вконтакте. Есть такой метод в API, `storage.set`, предназначен как раз для хранения настроек приложений.

**Comment by bodysome** [comment]
Какой быстрый ответ :)
Будет очень здорово, если Вы реализуете подобное. И чтобы скачивалось уже в _zip_, уйму места экономит (у меня ужалось в 10 раз; хотя это можно сделать и самому).

**Comment by bodysome** [comment]
И ещё есть просьба насчёт видео в сохр. переписке -- чтобы после обычной ссылки добавлялись _прямые_, со всеми доступными разрешениями (можно обойтись и одним, лучшим). Например:

[[video229291080_170902632] Peppa Pig listens to hurting music (0:35)] (http://vk.com/video229291080_170902632) → [[240]] (https://cs634106.vk.me/u229291080/videos/aa57e32e8b.240.mp4) [[360]] (https://cs634106.vk.me/u229291080/videos/aa57e32e8b.360.mp4) [[480]] (https://cs634106.vk.me/u229291080/videos/aa57e32e8b.480.mp4) [[720]] (https://cs634106.vk.me/u229291080/videos/aa57e32e8b.720.mp4)

Или другого, подобного вида. Спасибо :)

**Comment by Pmmlabs** [comment]
> И ещё есть просьба насчёт видео в сохр. переписке -- чтобы после обычной ссылки добавлялись прямые, со всеми доступными разрешениями

Ссылки не постоянны. Попробуйте перейти по ссылкам из вашего комментария - они все уже умерли.

**Comment by Kondra007** [comment]
У меня получение ссылок зависает для некоторых диалогов (на разных %)
Видимо, из-за мертвых ссылок. Но vkOpt не пропускает такие ссылки, тупо зависая.

Что делать?

**Comment by Pmmlabs** [comment]
@Kondra007 да, это было исправлено 16 июня: #151

**Comment by Pmmlabs** [comment]
В общем, начал я тут реализовывать эту функцию, и понял, что не стоит оно того.
Во-первых, скачивание всех фоток из диалога будет долгим, сохранение большого HTML с base64 - тоже.
Во-вторых, (как я уже говорил) у разных браузеров еще разные ограничения на максимальный размер картинки, хранящейся таким образом. То есть не факт, что фото в оригинальном расширении (а ссылки сохраняются именно на оригиналы) еще удастся нормально просмотреть потом. Да и сам HTML будет долго открываться.
Сжатие тут ничего не даст, т.к. картинки - самый плохосжимаемый тип файлов.
В-третьих, придется сильно переписывать функцию сохранения диалога, потому что скачивание - это асинхронная операция, придется всё на колбеках переписывать.

Гораздо легче и удобнее скормить генерируемую страницу программам типа Teleport Pro или Offline Explorer (или wget на Linux), которые скачивают сайты целиком. Там можно даже скачивать не только фото, а всё, на что есть ссылки, а также можно задать фильтр по расширениям, т.е. скачать например только фото и аудио, а остальное не трогать.
Так что считаю предлагаемую функцию бессмысленной.
