### ISSUE TITLE
Вопрос: почему вместо HEAD предпочитается GET с "Range: bytes=0-1"?

### ISSUE THREAD

**Issue by deltaidea** [VkOpt/VkOpt#195]
В 0c0baa850a7e815893b41b8df70b786353405adb и каком-то коммите до этого запросы методом `HEAD` заменяются на `GET` с заголовком `Range: bytes=0-1`. Зачем?

Пытался искать по коду, по Issues, пытался гуглить — ничего не нашёл.

**Comment by Pmmlabs** [comment]
Потому что иногда  HEAD возвращает 404. У меня, правда, такого никогда не было, и экстра настроечка включена.

**Comment by deltaidea** [comment]
Любопытно, спасибо.
А оно воспроизводится? Есть примеры таких урлов, которые стабильно 404 возвращают? Пока слабо верится.

**Comment by KiberInfinity** [comment]
Не запоминал адреса, но часть серверов ( может быть это кэш-сервера) отказывается отдавать инфу о файле при HEAD запросе.

**Comment by deltaidea** [comment]
Спасибо. Тогда звучит разумно.
