### ISSUE TITLE
Не открывается вкладка авторизации в Last.fm

### ISSUE THREAD

**Issue by Kantrael** [VkOpt/VkOpt#200]
Судя по всему, из-за нового дизайна их сайта.
![ux7k8uh 1](https://cloud.githubusercontent.com/assets/5757193/9572475/ff1c4ac8-4fb8-11e5-9efe-34f973f8c9e3.png)

**Comment by EgoAkk** [comment]
Известная проблема. Исправление уже готово - https://github.com/VkOpt/VkOpt/commit/bcfd322fb8a766a24b2088ea39200961a49e25eb . Ждите рабочую функцию в следующей версии.

**Comment by Kantrael** [comment]
Я могу сам как-нибудь собрать скрипт из исходников?

**Comment by EgoAkk** [comment]
@Kantrael, конечно. Инструкция в вики: https://github.com/VkOpt/VkOpt/wiki#%D0%A1%D0%B1%D0%BE%D1%80%D0%BA%D0%B0-%D1%80%D0%B0%D1%81%D1%88%D0%B8%D1%80%D0%B5%D0%BD%D0%B8%D1%8F-%D0%B8%D0%B7-%D0%B8%D1%81%D1%85%D0%BE%D0%B4%D0%BD%D0%B8%D0%BA%D0%BE%D0%B2

**Comment by Kantrael** [comment]
@EgoAkk Благодарю!
