### ISSUE TITLE
Замена "Мои" значками через CSS

### ISSUE THREAD

**Issue by Pmmlabs** [VkOpt/VkOpt#213]
Предлагаю заменять "Мои" в левом меню на значки средствами CSS, а не JS. Это реализовано тут: https://userstyles.org/styles/108456/theme 
Я посмотрел, хотел сам сделать, но чото запутался.

**Comment by Corak667** [comment]
Там ничего сложного, но все очень и очень печально.. Не думаю что кого-то будет такое устраивать (учитывая разные языки) и то что оно меняет размеры, а также требует наличие css3.
Вкратце:
1. Он делает размер шрифта оригинальных надписей 0px.
2. Инжектит область свой пак иконок, загруженные на savepic сайт и пододвигает их чтобы они надвигалась на надпись "Мои"
3. Инжектит перед оригинальными надписями свои исключительно русские "Cтраница", "Друзья":
Все инжектит он через CSS3 псевдоэлемент :before. 
http://htmlbook.ru/css3/before
![44bd3aebdca3 1](https://cloud.githubusercontent.com/assets/7928889/10054739/52d75164-623b-11e5-8071-a8e49c693009.png)

Скрывает лишние менюшки, фиксирует  размеры.
![fe22d95698af 1](https://cloud.githubusercontent.com/assets/7928889/10054884/1fd52c90-623c-11e5-82a7-0f8b28f53208.png)

**Comment by Pmmlabs** [comment]
Понятно, если через `content: `, то фигня.
> Но вот в его стиле есть мелкий недочет, конфликт с всплывашками в vkopt:

У меня нет конфликта. Установлена та тема.
