### ISSUE TITLE
Отображение списка аудио на странице поиска

### ISSUE THREAD

**Issue by RblSb** [VkOpt/VkOpt#236]
Кривое отображение всех элементов аудио, кроме того, на который наведена мышь (различная высота)
https://vk.com/search?c[q]=Pensees%20%E2%80%93%20Intro&c[section]=audio

![screen shot 2015-11-01 at 06 24 28](https://cloud.githubusercontent.com/assets/8753432/10867126/321ef76a-8063-11e5-9d8e-eb1d93a1c73e.png)
*****
![screen shot 2015-11-01 at 06 38 24](https://cloud.githubusercontent.com/assets/8753432/10867125/321e55e4-8063-11e5-8143-1d7bc0cc0732.png)

**Comment by Pmmlabs** [comment]
включи функцию "Уменьшить промежутки между аудио"

**Comment by RblSb** [comment]
@Pmmlabs тогда отображение везде слишком узкое, 30 пикселей вместо обычных 38 :(

**Comment by Pmmlabs** [comment]
@RblSb тогда что-то странное. Какой браузер? У меня на Firefox всё норально:
![default](https://cloud.githubusercontent.com/assets/2682026/10868319/5ab9a132-809c-11e5-9005-02ebfeb6ad64.png)

И я не вижу на втором скрине кнопки скачивания. Она тоже что ли пропадает?

**Comment by RblSb** [comment]
@Pmmlabs второй скрин это при отключенном вкопте, я забыл упомянуть. По умолчанию список более узкий, чем у теья на скрине.

**Comment by Pmmlabs** [comment]
@RblSb да, на 43 версии у меня тоже проблема есть. Но немного по-другому: элементы расползаются у текущей проигрываемой аудиозаписи.

**Comment by Pmmlabs** [comment]
@RblSb попробуй [этот коммит](https://github.com/Pmmlabs/VkOpt/commit/7db700c74eac82524c40517d0b2d8e6c1005d932). Вроде должно быть нормально

**Comment by RblSb** [comment]
@Pmmlabs исправлено, спасибо :)

**Comment by Pmmlabs** [comment]
да, я перенес кнопку скачивания из контейнера, в котором находится кнопка воспроизведения в контейнер с названием. Если уменьшить отступ между кнопками, то в случае отключенной опции "скачивание аудио" уменьшится отступ между кнопкой воспроизведения и названием. То  есть я пока не знаю, как сделать, чтобы было без потерь.  Как придумаю - создам PR, а пока надо еще потестить в разных браузерах.

**Comment by RblSb** [comment]
@Pmmlabs удачи :)
А как насчет переноса кнопки скачивания в место кнопок удаления и редактирования аудио?
![screen shot 2015-11-03 at 14 37 43](https://cloud.githubusercontent.com/assets/8753432/10907119/79b2e290-8238-11e5-9e70-cda45961a348.png)
Можно поместить перед этими двумя кнопками или за них.

**Comment by EgoAkk** [comment]
@RblSb есть куча мест где эти кнопки не показываются. А кнопка скачивания должна быть везде где есть кнопка плей.

**Comment by Pmmlabs** [comment]
Ну вроде всё исправлено? можно закрывать issue?

**Comment by RblSb** [comment]
@Pmmlabs агась, благодарю.
