### ISSUE TITLE
Firefox 43 дополнение не работает

### ISSUE THREAD

**Issue by apan65** [VkOpt/VkOpt#238]
Суть в заголовке, поставил 43тью бету лисы и дополнение перестало работать.

**Comment by Pmmlabs** [comment]
выключи режим e10s

**Comment by apan65** [comment]
http://c2n.me/3pP21Dw.png даже такого пункта нету, в about:config  ничего не нашел.

**Comment by Pmmlabs** [comment]
Отключать проверку подписей уже не требуется, последняя версия подписана.
Проверил сейчас на Developer Edition 43 и 44, везде работает. Бета - это же вроде и есть Developer Edition? Только вот у меня и в 43, и в 44 в настройках есть пункт "Enable multi-process Firefox Developer Edition", значит у тебя что-то другое. 
![default](https://cloud.githubusercontent.com/assets/2682026/10936962/f7ad7e1c-8300-11e5-8fc5-00243ceb3a40.png)

**Comment by apan65** [comment]
Нет, бета это не девелопер эдишн http://c2n.me/3pPvIpA.jpg
Скачана отсюда https://ftp.mozilla.org/pub/firefox/candidates/43.0b1-candidates/build1/win64/en-US/

**Comment by Pmmlabs** [comment]
скачал по этой ссылке, опять всё работает. Попробуй отключить все остальные расширения, может конфликтует что-то.
![default](https://cloud.githubusercontent.com/assets/2682026/10941971/f048c7e4-831e-11e5-80a0-c03209e797d8.png)

**Comment by apan65** [comment]
Интересная штука, выключил все дополнения кроме vkopt'а и всё-равно нифига не работает. Есть догадки в чём может быть причина?

**Comment by Pmmlabs** [comment]
Ну единственное, что я заметил - у тебя ОС восьмерка или десятка, а у меня семерка. Вообще это не должно влиять, но вдруг. 
И призываю @EgoAkk, он много знает про причины  неработоспособности.

**Comment by Pmmlabs** [comment]
@apan65 попробуй еще запустить firefox с ключом `-p` и создать новый профиль. Запусти на чистом профиле, установи туда vkopt и проверь, булет ли работать.

**Comment by apan65** [comment]
@Pmmlabs я уже проверил с чистым профилем, vkopt работает, но соответственно все настройки остальных дополнений теряются. Возможно как-нибудь оставить настройки дополнений, а всё остальное сбросить?

**Comment by Pmmlabs** [comment]
Можно наверное очистить куки и локальное хранилище для vk.com

**Comment by apan65** [comment]
Не помогло, а зачем локальное хранилище чистить, это же с adobe flash как-то связано?

**Comment by Pmmlabs** [comment]
Ну просто из того, что чистится при создании нового профиля, VkOpt использует только локальное хранилище и куки. С флешем это не связано, локальное хранилище - это как раз часть спецификации HTML5. 
В общем, не знаю я, как оставить настройки дополнений, единственное, можно попробовать перенести дополнения из одного профиля в другой (новый). https://forum.mozilla-russia.org/viewtopic.php?id=37152

**Comment by apan65** [comment]
В общем, я тут поковырялся и выяснил что причина глюка в одном или нескольких этих параметров.

user_pref("network.cookie.cookieBehavior", 2);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.dns.disableIPv6", true);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.dnsCacheEntries", 512);
user_pref("network.dnsCacheExpiration", 3600);
user_pref("network.http.max-connections-per-server", "16");
user_pref("network.http.max-persistent-connections-per-proxy", 256);
user_pref("network.http.pipelining", true);
user_pref("network.http.pipelining.abtest", true);
user_pref("network.http.pipelining.aggressive", true);
user_pref("network.http.pipelining.max-optimistic-requests", 3);
user_pref("network.http.pipelining.maxrequests", 12);
user_pref("network.http.pipelining.read-timeout", 60000);
user_pref("network.http.pipelining.reschedule-timeout", 15000);
user_pref("network.http.pipelining.ssl", true);
user_pref("network.http.proxy.firstrequest", true);
user_pref("network.http.proxy.pipelining", true);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.predictor.cleaned-up", true);
user_pref("network.predictor.enabled", false);
user_pref("network.prefetch-next", false);
user_pref("network.proxy.socks_remote_dns", true);
user_pref("network.proxy.type", 0);
user_pref("network.standard-url.escape-utf8", false);
user_pref("nglayout.debug.disable_xul_cache", false);
user_pref("nglayout.initialpaint.delay", 0);

**Comment by Pmmlabs** [comment]
у меня многие параметры отличаются:
network.cookie.cookieBehavior;0
network.dns.disableIPv6;false
network.dns.disablePrefetch;false
network.http.pipelining;false
network.http.pipelining.abtest;false
network.http.pipelining.aggressive;false
network.http.pipelining.max-optimistic-requests;4
network.http.pipelining.maxrequests;32
network.http.pipelining.read-timeout;30000
network.http.pipelining.reschedule-timeout;1500
network.http.pipelining.ssl;false
network.http.proxy.pipelining;false
network.http.speculative-parallel-limit;6
network.standard-url.escape-utf8;true
network.predictor.enabled;true

**Comment by apan65** [comment]
network.cookie.cookieBehavior - вот это виновник

**Comment by Pmmlabs** [comment]
Ну логично, network.cookie.cookieBehavior=2 запрещает использование cookie

**Comment by apan65** [comment]
Но соль в том что куки получались и отправлялись нормально.
