### ISSUE TITLE
Last.fm API key invalid

### ISSUE THREAD

**Issue by Manriel** [VkOpt/VkOpt#249]
Application has a broken API key for Last.fm:
> Invalid API key. If you are a third party developer see our authentication how-to to find out more.

Current api key: `8077e41f067a717abb49db6159081cb5`

**Comment by KiberInfinity** [comment]
![](http://ipic.su/ajGI6.png)

**Comment by Manriel** [comment]
Yes. Already fixed.
However, during last week that api-key was rejected by last.fm.
