### ISSUE TITLE
Плеер youtube

### ISSUE THREAD

**Issue by RblSb** [VkOpt/VkOpt#253]
После проигрывания видео функции плеера становятся недоступны из-за кнопок вк. Было бы неплохо сделать рамку под них, чтобы она не закрывала ничего другого.
![screen shot 2015-11-23 at 14 02 18](https://cloud.githubusercontent.com/assets/8753432/11335137/e2e6d87c-91ea-11e5-8c0a-3199ae01f0b4.png)

**Comment by Pmmlabs** [comment]
Можно вообще убрать эту панель, для этого надо убрать параметр enablejsapi=1 из iframe, а можно немного приподнять её, чтобы была видна нижняя часть проигрывателя - это делается через CSS.

**Comment by OwnageIsMagic** [comment]
Cудя по #255 тикет можно закрыть
