### ISSUE TITLE
Скрипт компиляции для 7zip

### ISSUE THREAD

**Issue by bykidi** [VkOpt/VkOpt#258]
Привет народ. Может кто написать скрипт сборки VKOpt'а из исходников через 7zip?
Спасибо!

**Comment by Corak667** [comment]
@bykidi Привет, я уже давно сделал свой автосборщик vkopt на batch (cmd) скриптинге (+wget, +7z) для Windows XP-7-8-10, если подходит, вот
http://files.leraux.ru/Corak/Soft/Network/VK/vkopt/vkopt_svn_updater.7z

**Comment by Pmmlabs** [comment]
Предлагаю сделать для сборки только один скрипт, который будет определять, какой инструмент доступен, и использовать его: python, winrar, 7z

**Comment by Corak667** [comment]
7z и wget тягать на такая уж проблема, как виндовые так и линуховые, весят не так уж и много. А питон будет актуален только для компиляции для хрома.

**Comment by EgoAkk** [comment]
Если для Хрома по любому нужен питон, то зачем распыляться и городить несколько билдеров. Меня устраивает сборщик на питоне. 
В любом случае кому то придётся что-то устанавливать дополнительно. Всем не угодить. Питон - универсальный и хороший вариант для разработчиков. В будущем через него можно будет завязать другой функционал (у меня есть планы). Я считаю что пользователям самим билдить нельзя (только понимающим для тестирования, но они уже не пользователи и для них нужно делать автобилдер на сервере), поэтому подстраиваться под всех не стоит. 

Я понимаю, что тут не все используют python, но я, например, так же не использую wget и разные разработчики используют разные архиваторы. Предлагаю остановиться на Python.

**Comment by Pmmlabs** [comment]
@EgoAkk а никто не говорит, что нужно выкинуть питон. Человек спросил про скрипт для 7z, потому что видимо, у него нет питона. Можно было бы написать скрипт, который при наличии питона паковал бы питоном, а при отсутствии - 7z-ом. Но я так понял, мы теперь отсеиваем "безпитонщиков".

**Comment by EgoAkk** [comment]
@Pmmlabs не правильно сначала прочитал. Ок, несколько вариантов имеет смысл сделать. 
Просто мой мессадж о том, что делать ВСЕ варианты будет излишним.
