### ISSUE TITLE
Язык lastFM'а в зависимости от языка VKOpt'а

### ISSUE THREAD

**Issue by bykidi** [VkOpt/VkOpt#262]
Сейчас, независимо от языка вконтакте и VKOpt'а все ссылки на lastfm ведут так:
http://www.last.fm/music/Ваш+Исполнитель
А хотелось бы что бы в зависимости от языка VKOpt'а ссылки адаптировались, например
VKOpt на русском языке, значит, и ссылка на lastfm будет тоже с русской локалькой
http://www.last.fm/ru/music/Ваш+Исполнитель

**Comment by bykidi** [comment]
оффтоп:
что за amo branch?

**Comment by EgoAkk** [comment]
> что за amo branch?
Ветка в которой дополнение под Firefox подписано Mozilla. Скоро это будет обязательным условием распространения дополнений.

**Comment by bykidi** [comment]
Либо ?setlang=ru

**Comment by bykidi** [comment]
ИМО бесполезно на фоне других функций vkopt'а которые ещё нужно будет реализовать, поэтому closed.
