### ISSUE TITLE
Firefox опять сломался  [ 45.0a2 ]

### ISSUE THREAD

**Issue by OwnageIsMagic** [VkOpt/VkOpt#264]
Привет всем из 45.0a2 
![default](https://cloud.githubusercontent.com/assets/10534634/11941148/9681e890-a83e-11e5-9f89-a745cf2a27a8.JPG)
Как видно из отладчика не подцепляет остальные фалы и рекурсивно вызывает ``VkOptInit``
При попытке вручную инициализировать естественно выдаёт ``ReferenceError: vkgetCookie is not defined`` и тд и тп
Версия последняя с сайта
В не e10s окне работает как обычно (#185 отвалился уже давно)

**Comment by Pmmlabs** [comment]
отключи e10s (мультипроцессность)

**Comment by OwnageIsMagic** [comment]
Совет хороший, но если дочитать до конца моё сообщение, то можно понять что он бесполезный.
Тем временем вышел новый билд ![default](https://cloud.githubusercontent.com/assets/10534634/11980106/5fe7601e-a9a9-11e5-9109-c65aeadd1154.JPG) в котором теперь уже крашит вкладку, а не просто не даёт завестись.

**Comment by Pmmlabs** [comment]
@OwnageIsMagic а если перейти по ссылке, которую я дал, или дочитать моё сообщение до конца (которое я отредактировал, как и ты), то можно понять, что бесполезный тут только ты.

На Linux кстати работает нормально с включенным e10s, значит, скоро и на Windows заработает.

**Comment by OwnageIsMagic** [comment]
Извини, что не ожидаю то что мне ответят в течении 5 минут и позволяю себе правки.
А если по делу, то я открываю https://github.com/VkOpt/VkOpt/releases и не вижу малейшего упоминания jetpack , затем я открываю https://github.com/VkOpt/VkOpt/downloads и вижу пустоту.
Я создал тему не потому что НИРАБОТАИТ, а потому что ещё вчера работало (иногда только приходилось вручную вызывать Init), а сегодня перестало.

**Comment by RblSb** [comment]
@OwnageIsMagic собираем под джетпак и радуемс :)
@Pmmlabs в 45 версии вроде вводят web extension api, будет ли вкопт перепиливатс под него? И не знаешь, доступна ли эта штука сейчас, или нужно ждать например бета-ветку лисы?

**Comment by OwnageIsMagic** [comment]
@RblSb А собранного нигде нет?
Я совсем не знаком с разработкой аддонов к FF.

**Comment by RblSb** [comment]
@OwnageIsMagic ну в этот раз собрал - http://dbwap.ru/493633
Мануал в вики
https://github.com/VkOpt/VkOpt/wiki

**Comment by OwnageIsMagic** [comment]
@RblSb А есть идеи почему так внезапно отвалилась старая версия? это ведь даже не изменение минорной версии

**Comment by RblSb** [comment]
@OwnageIsMagic мультипроцессорность вероятно допиливают, поэтому расширения и отваливаются. Зачем тебе ночная версия лисы?

**Comment by OwnageIsMagic** [comment]
@RblSb это не ночная, а аврора. Ночная дальше.
Потому что она на пол года опережает офф релиз, и много приятных плюшек в devtools.

**Comment by Pmmlabs** [comment]
@OwnageIsMagic В релизах этого нет, потому что эта версия  еще не релизилась, все релизы были на старой основе (XPCOM), которая работает со стабильной веткой FF. А для бета версии браузера - бета версия вкопта, всё логично. Бета-версия не предназначается для обычных пользователей, поэтому подразумевается, что её надо уметь собрать. Хотя "уметь" - громкое слово для инструкции из трех шагов. 
>у меня включена отправка телеметрии

На релизе тоже есть. Загляни в about:telemetry
> мультипроцессорность вероятно допиливают, поэтому расширения и отваливаются

Точно, e10s - всё ещё эксперимент, использовать который в повседневной жизни не нужно.

@RblSb про web extension api я знаю только то, что благодаря ему Firefox будет поддерживать установку расширений для Chrome. То есть, насколько я понимаю, ничего переписывать не надо будет - можно просто взять crx версию и установить. Не думаю, что при введении web extensions отвалятся старые фаерфоксовские расширения, поэтому скорее всего, нам ничего переделывать не придется. _(по крайней мере по этой части)_

**Comment by Pmmlabs** [comment]
@RblSb Сейчас почитал про WebExtensions, да, действительно уже в Nightly есть поддержка таких расширений. Кое-что всё-таки пришлось переделать для сборки такой версии вкопта, можете посмотреть в моей ветке [webext](https://github.com/Pmmlabs/VkOpt/tree/webext)
Но в целом у них идея такая: берем распакованное хромовое расширение, запаковываем его в xpi, и готово.
Сразу скажу, что расширение, собранное в вышеупомянутой ветке, не работает, потому что WebExtensions API еще не до конца реализовано: нет метода `chrome.extension.onRequest`, в то время как VkOpt его использует. Так что либо ждать реализации этого метода, либо переделать код, чтобы избежать использования.
