### ISSUE TITLE
Не работает отключение парсинга ссылок в диалогах

### ISSUE THREAD

**Issue by Scvairy** [VkOpt/VkOpt#272]
Без vkopt'а парсятся все ссылки на наличие видео/изображения или просто на то, что это ссылка и преобразуется в некую сущность, которая затем и прикрепляется к сообщению. С vkopt'ом картинки и видео парсятся только со второго раза, просто ссылки не преобразует вообще (а это не очень удобно, когда в ссылке есть ! или @ как в ссылках onedrive)

**Comment by Pmmlabs** [comment]
у тебя наверное включена функция, отключающая парсинг ссылок в диалогах. отключи в настройках.

**Comment by Scvairy** [comment]
А, и правда. Спасибо.
Тогда сформулирую по-другому: он с этой фукнцией ссылки частично парсит :D

**Comment by Pmmlabs** [comment]
Функция на самом деле уже не очень актуальна, потому что появилась возможность удалять миниатюры стандартными средствами. Просто раньше ее вообще не было, и по-любому миниатюра прикреплялась. 
А насчет того, что какие-то ссылки парсятся, ну не знаю, у меня пока что нормально всё с этим, может быть парсятся ссылки какого-то вида? приведи пример ссылки, которую функция пропускает.

**Comment by Scvairy** [comment]
Любая ссылка с изображением (или gif), вставленная два раза.
На самом деле, раз уж эта функция неактуальна, то может быть её нужно выпилить? :smile: 
Или чем больше фукнций - тем лучше? :hamster:

**Comment by Pmmlabs** [comment]
Картинки и гифки специально не затрагивались этой функцией, только внешние ссылки.
Выпилить можно, да. хотя функционал вконтакте по удалению миниатюр не в точности повторяет данную функцию (надо будет каждый раз нажимать крестик)

**Comment by Scvairy** [comment]
Ну тогда всё-таки проблема есть - эта функция всё-таки затрагивает картинки, гифки и видео: они появляются со второго раза. :D

**Comment by Scvairy** [comment]
Упс :confused:
