### ISSUE TITLE
` в названии файлов

### ISSUE THREAD

**Issue by iwex** [VkOpt/VkOpt#273]
Если ` присутствует в названии файлов - wget падает

**Comment by Corak667** [comment]
и еще символ ’
И еще весь Шведский, Норвежский, Японский  и все что конвертится в ?. Wget падает из-за нечитабельных символов синтаксиса и неподдерживаемых данной кодировкой (ansi например).

**Comment by Pmmlabs** [comment]
Кавычка уже была исправлена в пулле с каноничным номером #228
