### ISSUE TITLE
Кусок пространства внизу чата

### ISSUE THREAD

**Issue by stasleo** [VkOpt/VkOpt#274]
https://s.mail.ru/3pywQxEZ9cKS/img-2016-02-05-12-28-17.png

**Comment by RblSb** [comment]
Ого, хочу такую же, а то в нижнюю часть экрана некомфортно смотреть.

**Comment by EgoAkk** [comment]
Это именно из-за ВкОпта? Такого не будет если отключить совсем ВкОпт?
Такое во всех чатах?
При каких условиях появляется баг?
Может какая-то определённая функция влияет на это? Пробуйте отключать функции связанные с этим функционалом, пока баг не исчезнет.

**Comment by Pmmlabs** [comment]
@RblSb чтобы было также, достаточно потянуть вверх за палочки, которые под полем ввода текста

**Comment by bykidi** [comment]
У меня такое было из-за всплывающей новости, которая не закрывалась когда я курсор с неё убирал и оставалась на других страницах. Прогортай переписку в конец и закрой её.

**Comment by stasleo** [comment]
Похоже связано с включённым AdBlock для Google Chrome.
https://chrome.google.com/webstore/detail/adblock/gighmmpiobklfepjocnamgkkbiglidom
