### ISSUE TITLE
Кусок кода вместо скрытой аудиозаписи из "Рекомендуемых"

### ISSUE THREAD

**Issue by bykidi** [VkOpt/VkOpt#281]
1. Открываем ваши аудиозаписи
2. Жмем кнопку "Показать похожие" возле аудиозаписи
3. Жмем кнопку "Больше не показывать"
4. Вместо скрытой аудиозаписи получаем кусок кода как на скрине.
5. ...
6. profit

![default](https://cloud.githubusercontent.com/assets/1337953/14068096/f961a728-f480-11e5-8253-9ae81f4de943.PNG)

**Comment by bykidi** [comment]
Мои настройки

DefSetBits='yyyyynyyyyyyy0y0yy0yyyynyyyyyy0nynynnnyyy0yyy1nnnyynyy0yynynyynnnyynyyyyyyyyyyynnyn3nynyynyynyyyyyyyyyyyynyyn-7-11819233-#c5d9e7-#00aba8-1-------0';

**Comment by Pmmlabs** [comment]
Решено: #282

**Comment by bykidi** [comment]
Благодарю!
