### ISSUE TITLE
Вынос CSS из кода в отдельные файлы

### ISSUE THREAD

**Issue by uhbif19** [VkOpt/VkOpt#285]
CSS захардкожен в JS файлы, и применяется к странице из них. Из-за этого  страница после загрузки "мигает" и меняет свою верстку, что не есть хорошо.

**Comment by EgoAkk** [comment]
Весь css всё-равно зависит от включённых функций, так что применяться он так и так будет JSом...

**Comment by uhbif19** [comment]
И действительно. Ступил.
