### ISSUE TITLE
[FR] new.vk.com – новый интерфейс ВК

### ISSUE THREAD

**Issue by TrogWarZ** [VkOpt/VkOpt#287]
САБЖ. В Safari 9.1 нет ничего.

Плюс ошибка в консоли (не уверен, что это связано):
```
[Error] SyntaxError: Parser error
	eval (vk_lib.js:749)
	Make (vk_lib.js:749)
	Before (vk_lib.js:787)
	vkStManHook (vk_main.js:22)
	VkOptMainInit (vk_main.js:262)
	VkOptInit (vkopt.js:572)
```

**Comment by Pmmlabs** [comment]
@TrogWarZ см. #286 
новый интерфейс будем обсуждать там. Пока ничего не работает, но мы работаем над этим.
