### ISSUE TITLE
Плохо парсятся ссылки с AliExpress

### ISSUE THREAD

**Issue by bykidi** [VkOpt/VkOpt#288]
Вот такое... Народные умельцы, реально ли это поправить с помощью вкопта?
![default](https://cloud.githubusercontent.com/assets/1337953/14316165/432a3254-fc0a-11e5-991e-5f5579d5bb18.PNG)

**Comment by bykidi** [comment]
Оригинал ссылки

[code]http://ru.aliexpress.com/item/Men-s-hooded-with-a-black-gown/32565189744.html?spm=2114.03010208.3.2.813ueB&ws_ab_test=searchweb201556_1,searchweb201602_4_10017_10005_10006_10034_10021_507_10022_10020_10007_10018_10019,searchweb201603_2&btsid=2a1c1128-0206-4b63-9273-82edab73e959[/code]

**Comment by EgoAkk** [comment]
Как по мне - такие вещи должны править ВК или сами Али. 
Разрешать запятую в урле - это создаст ещё больше битых ссылок в предложениях где люди просто разделяли ссылки запятыми.

**Comment by Pmmlabs** [comment]
@bykidi я согласен с @EgoAkk, но если уж очень хочется, то можно воспользоваться моим плагином для подсветки неподвечиваемого (и частично подсвечиваемого) https://gist.github.com/Pmmlabs/d10158413321e2d74f96
только там надо будет на 40 строке в массив добавить еще
`/http:\/\/.*.aliexpress.com/`

**Comment by bykidi** [comment]
Ни VK, ни Ali за всё время существования данной ошибки ничего не сделали. Открываю исс заново, вдруг палка выстрелит и это реально будет исправить

**Comment by KiberInfinity** [comment]
Предлагаю убивать из ссылки на товар все реферы при вставке в поле.

**Comment by bykidi** [comment]
Без мусора после .html?XXXX всё идеально парсится с превьюшками. Я только за, потому как каждую ссылку нужно для удобности собеседника обрезать руками

**Comment by OwnageIsMagic** [comment]
@bykidi https://addons.mozilla.org/ru/firefox/addon/clean-links/
сам не пользовался, под хром я думаю что-то похожее есть

**Comment by OwnageIsMagic** [comment]
@bykidi магии реально не существует
или разрешить запятую в парсере ссылок и сломать жизнь любителей запятой 
или добавить спец правило для ali чистящее реферы при отправке

**Comment by OwnageIsMagic** [comment]
что я делаю не так?
![image](https://cloud.githubusercontent.com/assets/10534634/20584673/21f60114-b206-11e6-93ec-37fb38e8591c.png)

**Comment by bykidi** [comment]
Firefox?

**Comment by OwnageIsMagic** [comment]
Да
Но это Вк на сервере убирает текст ссылки

**Comment by bykidi** [comment]
Действительно? Попробую с другими браузерами без аддона чуть позже.

//edit Проверил на Firefox 50 - всё снова хорошо парсится.

**Comment by bykidi** [comment]
Думается мне, можно закрывать

**Comment by OwnageIsMagic** [comment]
Забавно
 только сейчас заметил что это интеграция с али со стороны вк, а не просто случайный фикс
Так что ваши жалобы в суппорт были учтены
