### ISSUE TITLE
Потеря совместимости с palemoon

### ISSUE THREAD

**Issue by Bfgeshka** [VkOpt/VkOpt#289]
Коммит за 4.04 заставляет работать с джетпаком и начиная с него билды перестают работать с palemoon - ни простая, ни jetpack-версия не работают никак.

**Comment by KiberInfinity** [comment]
а palemoon  джетпак не держит?

**Comment by Bfgeshka** [comment]
Ну есть, наверное, нюансы.

Старая схема работает без пререканий и по сути больше всего интересует.

**Comment by KiberInfinity** [comment]
Джетпак уже пофиксил и запустил на palemoon, только всплыли ещё баги (нарушена коммуникация между скриптами на сайте и контент скриптом расширения)

**Comment by KiberInfinity** [comment]
Запускабельное, но видать не полноценно (у меня битрейт не определяется)
https://github.com/VkOpt/VkOpt/commit/400c9c7521979dfa19a3438ec505fd290c2a44dd

**Comment by Bfgeshka** [comment]
Вот теперь не-jetpack запускается. Да, похоже, что битрейт действительно не ловится, но больше косяков не видно.

**Comment by KiberInfinity** [comment]
неJetpack'а теперь нет. в builds/firefox, тоже лежит вкопт на основе джетпака, только немного по другому реализован он.

**Comment by Bfgeshka** [comment]
Я говорю то, что есть; во внутренности кода залезать не стал, но дела вот так и обстоят - то, что было с суффиксом jetpack, снова не сработало, а обычный билд пашет. Хорошо бы их переименовать для очевидности - быть может, добавить суффикс legacy или вроде того.

**Comment by Pmmlabs** [comment]
Коммит 1a91d5e884d43d386ada4702d81b4b9e4c8b62bd ломает мой джетпак (то, что с суффиксом jetpack), и после него  в принципе работает только одна версия, без суффикса

**Comment by KiberInfinity** [comment]
@Bfgeshka 
Обновил. d655d06e2432d0d00c68deee798e9a410dd34384 теперь вроде бы на palemoon полноценно работает.

@Pmmlabs 
Вероятно из-за правок в бекграунде?

**Comment by Pmmlabs** [comment]
@KiberInfinity скорее всего. больше не из-за чего.

**Comment by Bfgeshka** [comment]
@KiberInfinity
Действительно, против коммита d655d06 простая версия работает и битрейт стал показываться, однако против последнего bbf8f25 не работает ничего.

**Comment by KiberInfinity** [comment]
@Bfgeshka  а сейчас?

**Comment by Bfgeshka** [comment]
@KiberInfinity
Теперь на e6004a8 снова работает обычный билд.

**Comment by AsukaLangleyfag** [comment]
Поднимаю тред, сейчас аддон не ставится в Palemoon как jetpack, при установке через https://github.com/JustOff/moon-tester-tool/ не работает.
