### ISSUE TITLE
Перестал работать пункт "Добавить в группу" на аудио

### ISSUE THREAD

**Issue by Kondra007** [VkOpt/VkOpt#295]
Версия 2.3.3.1 с сайта. Ставил из этого репозитория - та же фигня. Просто ничего не происходит при нажатии.
Браузер: Chrome

**Comment by KiberInfinity** [comment]
Хм. Вчера проверял эту же функцию на новой версии сайта, работала

**Comment by Kondra007** [comment]
Забавно. В новой версии сайта вообще не вижу этот пункт, а не работает в старой.
Я про это меню говорю, если что.
![image](https://cloud.githubusercontent.com/assets/2780044/15451190/9a2412d2-1fbe-11e6-83b0-d992173d7ef0.png)

**Comment by KiberInfinity** [comment]
на старой версии сайта тоже работает. только что проверил

**Comment by KiberInfinity** [comment]
в новой версии сайта в последнем коммите из ветки ver3 добавлено.

**Comment by Kondra007** [comment]
Может, установилось как-то не так у меня? Кстати, нажатие на кнопку "Сохранить настройки на сервере" вообще никак себя не проявляет (это нормально?)

**Comment by KiberInfinity** [comment]
хм. если отвалилось апи, то всё объясняется

**Comment by Kondra007** [comment]
Нет, всё-таки какая-то фигня с Хромом. Поставил расширение в Firefox – всё работает. Вы не могли бы проверить у себя в Chrome?

**Comment by KiberInfinity** [comment]
Работает. Можно попробовать локальное хранилище vk.com почистить

**Comment by Kondra007** [comment]
Та же фигня. Ладно, раз это у Вас не воспроизводится, буду искать проблему у себя. Спасибо за оперативный ответ!

**Comment by Kondra007** [comment]
Кстати, на новом дизайне (из ветки ver3) добавление в группу работает, а в старом по-прежнему нет. Чудеса.

И отдельное спасибо за избавление от округлостей (в настройках ver3)
