### ISSUE TITLE
[master/ver3] Не появляется всплывашка об авторизации на LastFM

### ISSUE THREAD

**Issue by bykidi** [VkOpt/VkOpt#296]
Тайтл. Не пашет и всё тут. Юзаю Waterfox x64 46.0.1
Тестил на ver3 и master. Хинт пишет что нужна авторизация.

**Comment by KiberInfinity** [comment]
А если локальное хранилище почистить от записей с иенами, в которых есть 'lastfm' и попробовать ещё раз, после обновления страницы?

**Comment by bykidi** [comment]
Не помогает.

**Comment by KiberInfinity** [comment]
блокировщики рекламы какие-то стоят?

**Comment by bykidi** [comment]
uBlock Origin

**Comment by bykidi** [comment]
Действительно, проблема была в нем. Осталось найти нужный фильтр, который дает сбой.
