### ISSUE TITLE
Не сохраняются настройки

### ISSUE THREAD

**Issue by ForumLiker** [VkOpt/VkOpt#297]
После выхода из аккаунта и закрытия вкладки браузера firefox, зайдя снова в аккаунт вк, скрипт предлагает выбрать язык - настройки скрипта сбились. Как то можно задать нужные мне настройки чтобы сразу были по умолчанию?

**Comment by EgoAkk** [comment]
ВК сделали сами очистку куков и всех локальных настроек при логауте. 
Пока их можно только сохранить на сервер или в файл, что бы потом быстрее их восстанавливать.

В следующей версии будет реализовано хранение настроек в хранилище расширения и тогда ВК не сможет их очищать...

**Comment by ForumLiker** [comment]
Спасибо за ответ.
