### ISSUE TITLE
Невозможно выбрать переписку после удаления другой переписки

### ISSUE THREAD

**Issue by bykidi** [VkOpt/VkOpt#298]
1. Открываем new.vk.com/im
2. Открываем переписку с любым человеком
3. Удаляем эту переписку
4. Пытаемся открыть другую переписку
5. ...
6. Профит.
7. Что бы открыть новую переписку нужно обновить страницу

Waterfox 47.0 RC x64
Без VKOpt'а всё ок.
Может кто-нибудь подтвердить?

**Comment by KiberInfinity** [comment]
При удалении на Opera 37 в консоли только одна ошибка:
!()[http://savepic.ru/10108787.png]

Но диалоги потом открываются

**Comment by bykidi** [comment]
Не думаю что это ещё актуально, поэтому закрыто
