### ISSUE TITLE
Статистика UA

### ISSUE THREAD

**Issue by OwnageIsMagic** [VkOpt/VkOpt#299]
Можете предоставить статистику по юзер агентам пользователей вкопта?
для того что бы писать на ES5 диалекте и присылать код не из бабеля.

**Comment by EgoAkk** [comment]
Что-то я не до конца понял, с какой целью Вы интересуетесь такой статистикой, конкретно по ВкОпту? 
Мы не храним и тем более не распространяем такую информацию посторонним людям.

**Comment by OwnageIsMagic** [comment]
Если промисы ещё можно спрятать за `if (window['Promise'])` 
то ключевое слово `await` от парсера его не поддерживающего не спрячешь никак.
В связи с этим хочу узнать смогут ли другие пользователи воспользоваться моим кодом.

**Comment by KiberInfinity** [comment]
Не хотелось бы без необходимости  подобный код добавлять в расширение, т.к новые стандарты сам вк ещё не использует, и хотелось бы примерно на таком же уровне и код расширения оставить.

**Comment by OwnageIsMagic** [comment]
@EgoAkk Вы не храните, а они хранят
http://rating.openstat.com/site/2050482/

**Comment by KiberInfinity** [comment]
@OwnageIsMagic на мой взгляд вопрос был опущен из-за того, чтоб смотреть не на новые возможности ES6, а на используемые самим вк стандарты, чтоб скрипты можно было запустить на том же, на чём и работает десктопная версия вк. 
З.Ы. на Maxthon'е у меня в просмотрщике фото почему-то не открывается меню "Ещё" даже без вкопта.

**Comment by OwnageIsMagic** [comment]
@KiberInfinity да мне хотя бы es5
а то смотришь на https://github.com/VkOpt/VkOpt/blob/master/source/vk_lib.js#L365
и задумываешься..
