### ISSUE TITLE
Мусор в глобальном пространстве имён

### ISSUE THREAD

**Issue by OwnageIsMagic** [VkOpt/VkOpt#301]
Было бы круто перенести используемые только в одном месте глобальные переменные и однотемные функции в отдельные объекты
например:
```
function vkHidePhoto() 
function vkShowProfile(el,html,uid,right)
function vkPopupAvatar(id,el,in_box)
//глобальные переменные объявленные без var  😞
allowHidePhoto=setTimeout(null,null);
allowShowPhotoTimer=setTimeout(null,null);
cur_popup_idx=0;
cur_popup_url=null;
```
Вызываются только между собой и смысла вызывать их из внешнего кода нет
Мог бы и поправить сам, но маленькие команды имеют особенность блокировать всё, что ломает обратную совместимость
Поэтому решил сначала спросить

**Comment by KiberInfinity** [comment]
Под новый дизайн делается более кучно. Старый код будет удалён после отключения старого дизайна.

**Comment by OwnageIsMagic** [comment]
А есть планы по переводу проекта из стихийной разработки к чему либо на подобие roadmap?

**Comment by KiberInfinity** [comment]
Планы то есть, Нормально сесть и создать таски руки не доходят. Да и то пока не определились - здесь в Issues создавать, или на форуме в модуле проектов.

**Comment by OwnageIsMagic** [comment]
Ближе к коду
Просто создать 1 тикет с чекбоксами

- [x] Сделать всё
- [ ] йцу
- [ ] 123

```
- [x] Сделать всё
- [ ] йцу
- [ ] 123
```

**Comment by bykidi** [comment]
тест
- [x] всем привет
- [x] уволить дурова
- [ ] вернуть стену

**Comment by bykidi** [comment]
Работает!

**Comment by OwnageIsMagic** [comment]
@bykidi Если они в первом посте то ещё на тикете отображается полоска прогресса

**Comment by OwnageIsMagic** [comment]
https://github.com/blog/2206-reorder-issues-within-a-milestone
Теперь ещё можно менять приоритеты

**Comment by OwnageIsMagic** [comment]
@bykidi а теперь ещё и так https://github.com/VkOpt/VkOpt/projects
