### ISSUE TITLE
Названия настроек

### ISSUE THREAD

**Issue by Kondra007** [VkOpt/VkOpt#305]
Вопрос: это у меня криво установилось дополнение, или так и должно быть, что в разделе "Extra" опции названы "переменными", а не в читаемом виде?

![image](https://cloud.githubusercontent.com/assets/2780044/17272062/6217c25e-5695-11e6-9083-96b8ef03e533.png)

**Comment by EgoAkk** [comment]
Это нормально. Раздел Exstra в релизе скрытый и доступен только через ручной поиск по настройкам.

**Comment by Kondra007** [comment]
В релизе? В каком релизе? Использую сейчас ветку **ver3**, а **master** вообще не работает в новом дизайне.

**Comment by EgoAkk** [comment]
Ну релиза для нового дизайна нет. Соответсвенно раздел скроют перед релизом :)
Это опции не для общего пользования и их не будет в списке настроек.

**Comment by Kondra007** [comment]
@EgoAkk а, окей, спасибо. А то у меня эти настройки в общем списке отображаются, ничего не скрыто изначально было.
