### ISSUE TITLE
День Х

### ISSUE THREAD

**Issue by OwnageIsMagic** [VkOpt/VkOpt#307]
вк наконец перевёл всех на новый дизайн
можно полностью выпиливать костыли оставшиеся от старого дизайна

**Comment by bykidi** [comment]
RIP

**Comment by OwnageIsMagic** [comment]
_offtop_
![aaaa](https://cloud.githubusercontent.com/assets/10534634/17723232/3853c602-6441-11e6-8c64-206175bde13e.JPG)
это были его последние слова

**Comment by apan65** [comment]
Новый дизайн - планшетная жуть, столько пустых промежутков, сократить бы все эти расстояния в новостной ленте.
