### ISSUE TITLE
Функция подписки на стены с новым дизайном.

### ISSUE THREAD

**Issue by apan65** [VkOpt/VkOpt#309]
Возможно ли вернуть эту безусловно полезную фичу в новую ветку скрипта? Я так понимаю планируется вернуть прежний функционал? Или от чего-то планируется избавиться?

**Comment by OwnageIsMagic** [comment]
эта функция добавилась официально
На страницах теперь есть кнопка Подписаться или что-то вроде этого
![ddddd](https://cloud.githubusercontent.com/assets/10534634/17728023/afd1d6e6-6465-11e6-9b12-7b21b757e6d6.JPG)
и что-то похожее есть для групп

**Comment by apan65** [comment]
> эта функция добавилась официально
Там вроде как есть пункт получать уведомления, но не понятно, как это будет работать, в новостной ленте будут записи появляться?

**Comment by OwnageIsMagic** [comment]
по идее вот здесь
![123](https://cloud.githubusercontent.com/assets/10534634/17728570/80a74b96-6468-11e6-9c69-484abaea9ed3.JPG)

**Comment by apan65** [comment]
> по идее вот здесь

Не очень идея, как по мне, просто захламлять уведомления, они не для этого созданы.

**Comment by OwnageIsMagic** [comment]
а как это было реализовано в вкопте?

**Comment by apan65** [comment]
> а как это было реализовано в вкопте?
В новостной ленте появляются посты в хронологическом порядке, как от сообществ и друзей. Например мне нужна группа с сообщениями на её стене, я от группы отписываюсь и подписываюсь скриптом, в итоге у меня все сообщения в группе есть в новостной ленте.

**Comment by OwnageIsMagic** [comment]
![123](http://www.online-vkontakte.ru/wp-content/uploads/2014/11/%D0%9A%D0%B0%D0%BA%D1%81%D0%BA%D1%80%D1%8B%D1%82%D1%8C%D0%B3%D1%80%D1%83%D0%BF%D0%BF%D1%8B%D0%92%D0%BA%D0%BE%D0%BD%D1%82%D0%B0%D0%BA%D1%82%D0%B51.png)
или зачем ещё отписываться?

**Comment by apan65** [comment]
> или зачем ещё отписываться?

Ну в принципе можно не отписываться, а просто скрыть новости группы, чтобы не дублировались, а не в целях приватности.

**Comment by OwnageIsMagic** [comment]
я не понял
зачем скрывать новости, если хочешь их смотреть, причём в той же ленте
текущий вариант мне представляется более удобным, т.к. позволяет не пропускать новости от групп пишущих не часто _(а я вообще в ленту не заглядываю)_

**Comment by Pmmlabs** [comment]
Потому что в ленте появлялись сообщения со стены сообщества от обычных людей

**Comment by OwnageIsMagic** [comment]
так бы сразу и сказали

**Comment by EgoAkk** [comment]
Давайте не будем тут заводить таски на каждую функцию, которая была в прошлой версии. 
И так уже сказали, что будем переносить ВСЕ старые функции. 
Давайте тут обсуждать технические баги в коде и присылать пулл реквесты со сделанными функциями и исправлениями. 

А то тут можно так пару сотен тасков поназаводить и потеряться в них. На форуме вон уже навели хаос своими хотелками :)

Спасибо

**Comment by RblSb** [comment]
@EgoAkk знать бы как делать(
