### ISSUE TITLE
Добавить генерацию списка аудио с альбома

### ISSUE THREAD

**Issue by vSkyD1** [VkOpt/VkOpt#310]
В дополнение к 79d5946f0836d5590a9f75e6ffb8538a86aa4b80

В идеи, при нажатии на соответствующую иконку (№1) должен появится список аудио из альбома (№2) в текущий плейлист.

Я думал, на счет составления списка с помощью поиска (vk.com/search?c[q]=Twenty%20One%20Pilots%20-%20Stressed%20Out&c[section]=audio), но ВК ищет только по одному аудио... 

![](http://i.imgur.com/KFULFYc.png)

**Comment by EgoAkk** [comment]
Так такое было уже в прошлой версии. По одной искало и составляло список.

**Comment by vSkyD1** [comment]
Тогда отлично. Буду ждать реализации
