### ISSUE TITLE
Определение битрейта аудиозаписи по наведению

### ISSUE THREAD

**Issue by Vasfed** [VkOpt/VkOpt#311]
В старой версии была полезная фича - битрейт трека считался по наведению на длительность, это неплохой компромисс между загрузкой вообще всех битрейтов и полным их отсутствием, т.к. сокращает количество запросов к вк и траф/нагрузку на клиента, оставляя собственно возможность узнать инфу.

Триггер можно оставить тот же - ховер `.audio_acts` или даже самого `.audio_info`

**Comment by OwnageIsMagic** [comment]
если нажать Ctrl треки с 320kb/s помечаются меткой HQ

**Comment by EgoAkk** [comment]
Давайте не будем тут заводить таски на каждую функцию, которая была в прошлой версии. 
И так уже сказали, что будем переносить ВСЕ старые функции. 
Давайте тут обсуждать технические баги в коде и присылать пулл реквесты со сделанными функциями и исправлениями. 

А то тут можно так пару сотен тасков поназаводить и потеряться в них. На форуме вон уже навели хаос своими хотелками :)

Спасибо
