### ISSUE TITLE
вернуть старые обозначения непрочитанных сообщений в списке

### ISSUE THREAD

**Issue by OwnageIsMagic** [VkOpt/VkOpt#312]
фон сообщения - непрочитанное моё
фон всего элемента списка - непрочитанное входящее
как-то так
`<div class="nim-dialog--cw" style="background: #deedfeef;">`

**Comment by EgoAkk** [comment]
Давайте не будем тут заводить таски на каждую функцию, которая была в прошлой версии. 
И так уже сказали, что будем переносить ВСЕ старые функции. 
Давайте тут обсуждать технические баги в коде и присылать пулл реквесты со сделанными функциями и исправлениями. 

А то тут можно так пару сотен тасков поназаводить и потеряться в них. На форуме вон уже навели хаос своими хотелками :)

Спасибо

**Comment by OwnageIsMagic** [comment]
ну это был дизайн вк, а не фича вкопта
присылать пул реквесты способны всего 2 человека
это те кто писал этот код, т.к. сейчас что бы понять как это работает надо просмотреть 5к строк `vkopt.js + vk_lib.js`
на счёт пары сотен тасков - в чём проблема?
тут есть нормальный поиск по ним - сделал фичу, написал в описании комита Fixes #312 и гитхаб сам закрыл соответствующий issue

**Comment by OwnageIsMagic** [comment]
месяца 4 назад писал писал голосовые оповещения о входящих сообщениях
пока писал нашёл 5 разных способов преобразовать id в имя+фамилию, причём из-за особенностей их реализации, пришлось напедалить свой

**Comment by OwnageIsMagic** [comment]
@EgoAkk  например:
очень хочу вернуть переключение раскладки на Ctrl+Q
Где можно найти старый код отвечающий за это?

**Comment by Pmmlabs** [comment]
@OwnageIsMagic поставь Punto Switcher

**Comment by OwnageIsMagic** [comment]
@Pmmlabs я вытащил их в букмарклет
