### ISSUE TITLE
UA matcher

### ISSUE THREAD

**Issue by OwnageIsMagic** [VkOpt/VkOpt#314]
https://github.com/VkOpt/VkOpt/blob/master/source/vk_lib.js#L197
Аналогичная структура существует в https://vk.com/js/al/common.js#L46  (`var browser = {`)
есть особый смысл хранить её отдельно?

**Comment by KiberInfinity** [comment]
Есть места, где определение браузера нужно, когда common.js ещё не существует в контексте страницы.
