### ISSUE TITLE
VKOPT_CFG_LIST is not defined

### ISSUE THREAD

**Issue by OwnageIsMagic** [VkOpt/VkOpt#317]
`ReferenceError: VKOPT_CFG_LIST is not defined`  `upd_mozila.js:354`
да и сам фикс не работает
загружает на сервер обе картинки и обе открепляет от сообщения

**Comment by KiberInfinity** [comment]
@OwnageIsMagic, 
эм. он вообще не должен подтягиваться.
сейчас должен быть только upd_fixes.js

**Comment by OwnageIsMagic** [comment]
а есть шанс что, `typeof prepareAudioLayer != 'undefined'` которое вроде как эквивалентно
`prepareAudioLayer != undefined //или void 0`
может ещё не инициализироваться на момент `vkopt_core.run()`?

**Comment by OwnageIsMagic** [comment]
хз крч
я специально тоже не тянул его
перезапустил браузер - всё ок
я думаю дело в том что common.js парсится позже
![gh](https://cloud.githubusercontent.com/assets/10534634/17928704/abfdbacc-6a04-11e6-87ff-ac09d1cf09cd.JPG)
а когда
![](https://pp.vk.me/c630916/v630916573/4850b/SuhQzApzWmY.jpg)

у браузера 6 часов аптайма это вполне может повлиять

**Comment by KiberInfinity** [comment]
надо будет остальные варианты выпилить.

**Comment by OwnageIsMagic** [comment]
проблема в том что мы вполне можем оказаться перед common.js при парсинге
