### ISSUE TITLE
WebExtensions

### ISSUE THREAD

**Issue by OwnageIsMagic** [VkOpt/VkOpt#320]
![gh](https://cloud.githubusercontent.com/assets/10534634/17995403/1ea8711e-6b6a-11e6-9780-f6938c9327a4.JPG)
https://developer.mozilla.org/en-US/Add-ons/WebExtensions
48 это текущий stable
Как я понял можно просто оставить только Chrome ветки в `content_script` и паковать как WebExtension универсально для всех браузеров
немного ссылочек на всяк случай
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Anatomy_of_a_WebExtension#Content_scripts
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Content_scripts

**Comment by EgoAkk** [comment]
Я подробно не вдавался в детали, но нет ли там каких-либо ограничений по сравнению с нативными дополнениями?

**Comment by OwnageIsMagic** [comment]
нет
это просто запуск хромовых аддонов в ФФ

**Comment by OwnageIsMagic** [comment]
судя по http://www.arewewebextensionsyet.com/
единственный метод который ФФ не поддерживает это `chrome.extension.onRequest`
но
![gh](https://cloud.githubusercontent.com/assets/10534634/17995835/a466f106-6b6d-11e6-9b38-7f875ef86435.JPG)

> Not implemented: This is not implemented in Firefox because it has been deprecated since Chrome 33. Please use runtime.onMessage instead.

**Comment by EgoAkk** [comment]
Ну это то понятно. Главное что бы это не было сделано через какую-то прослойку, которая ретранслирует все действия и теряет доступ к половине апи. 

Судя по доке, они уже потеряли доступ к половине High-Level APIs из Add-on SDK, не говоря уж об Low-Level APIs. Но нам то пофиг, мы почти ничего там не используем. 
Хотя, опять-таки, судя по доке, они собираются полностью перейти на WebExtensions в будущем. 

Но самая главная проблема - это потеря совместимости со всеми старыми версиями FF и кучей форков, основанных на Gecko (SeaMonkey, K-Meleon и т.д.). Так что если даже и переходить на WebExtensions, то всё-равно придётся суппортить пока две сборки.

**Comment by Pmmlabs** [comment]
Я уже пробовал завести webextensions, не получилось https://github.com/VkOpt/VkOpt/issues/264#issuecomment-167091204

**Comment by OwnageIsMagic** [comment]
> High-Level APIs из Add-on SDK, не говоря уж об Low-Level APIs
@EgoAkk Ну я так и написал, 'поддержка аддонов хрома' )
@Pmmlabs поддержка сборки как WebExtension означает добавление Edge
посмотрел твою ветку, ты там пакуешь в xpi, а у хрома зип
я думаю он тип аддона по расширению файла определяет
сейчас попробую у себя запустить

**Comment by OwnageIsMagic** [comment]
и ещё мне лень копаться, может объяснит кто
В чём разница между хромовым аддоном и для оперы?
или это для той которая на Presto?

**Comment by EgoAkk** [comment]
@OwnageIsMagic отдельное расширение для Оперы - это для той что на Presto ещё. 
А для последней Оперы используется расширение под Хром

**Comment by OwnageIsMagic** [comment]
@Pmmlabs у меня всё завелось
content_script встраисается и запускается раньше всех
![gh](https://cloud.githubusercontent.com/assets/10534634/17998121/6eb85fd2-6b7b-11e6-9fd2-8ab63e332cc0.JPG)

**Comment by OwnageIsMagic** [comment]
Абсолютно нормально всё работает
сейчас вспомню что написал в консоль что бы притвориться хромом и ПР пришлю

**Comment by apan65** [comment]
Я пробовал дополнения хрома ставить на лису, работают, но не все, подписать иногда проблемно правда.

**Comment by OwnageIsMagic** [comment]
@apan65 моя ветка уже в мастере,  всё ок

**Comment by OwnageIsMagic** [comment]
Или нет, но тогда лучше коментить в PR выше
