### ISSUE TITLE
Поддержка e10s в Firefox

### ISSUE THREAD

**Issue by Oreolek** [VkOpt/VkOpt#327]
Firefox переходит на мультипроцессы, VkOpt их не поддерживает из-за Jetpack.

**Comment by OwnageIsMagic** [comment]
VkOpt собирается как webext, так что всё ок

**Comment by KiberInfinity** [comment]
кстати, а webext  тоже подписывать надо через их сервер?

**Comment by Oreolek** [comment]
вроде да. Дополнение [Addon Compatibility](https://addons.mozilla.org/en-US/firefox/addon/add-on-compatibility-reporter/) говорит, что VkOpt "is incompatible with multiprocess"

**Comment by Pmmlabs** [comment]
мы вообще-то и перешли на jetpack из-за того, что в этом формате расширение поддерживается в режиме e10s. может с новыми версиями FF перестало поддерживается, но изначально было именно так

**Comment by KiberInfinity** [comment]
@Pmmlabs у фаерфокса джетпак сейчас сводится к тому, что бутстраповская оболочка импортится из недр ресурсов браузера. У некоторых форков фаерфокса, этих ресурсов нет, и по этому своя версия бутстраповского скрипта лежит у нас в расширении. 
Может валидатор из-за этого возмущается?

**Comment by OwnageIsMagic** [comment]
Подписывать точно так же

**Comment by bykidi** [comment]
Простите за bump, но какой сейчас статус e10s в огнелисе? Addon Compatibility всё ещё жалуется на Incompatible with e10s.

**Comment by OwnageIsMagic** [comment]
https://wiki.mozilla.org/Electrolysis
в релизной ветке включён по умолчанию на чистых установках начиная с августа 2016

**Comment by bykidi** [comment]
@OwnageIsMagic а если производить апгрейд со старым профилем - включается ли он автоматически? потому как на моем стареньком waterfox (ноут) и cyberfox (рабочий комп) e10s не включился автоматом, а на домашнем компе в том же waterfox проявляются черные квадраты-артефакты

**Comment by OwnageIsMagic** [comment]
Там по ссылке есть таблица в которой описывается когда фф включает его сам. 
Незнаю как в форках обстоят дела, они вполне могут вообще не включать его

**Comment by RblSb** [comment]
В FF Nightly VkOpt отключается как не поддерживающий мультипроцессорность
https://wiki.mozilla.org/Add-ons/ShimsNightly
