### ISSUE TITLE
whitespace

### ISSUE THREAD

**Issue by OwnageIsMagic** [VkOpt/VkOpt#328]
Михаил, прошу вас
в `shortcuts.xml` можно изменить бинд на `Ctrl+S`
![default](https://cloud.githubusercontent.com/assets/10534634/18585443/9f3fb272-7c1f-11e6-9676-28b2c46f5ba5.JPG)
upd:
или тут
![default](https://cloud.githubusercontent.com/assets/10534634/18587216/7c361b68-7c29-11e6-8eab-ff577a7f0715.JPG)

**Comment by KiberInfinity** [comment]
Спасибо)
