### ISSUE TITLE
рефактор настроек

### ISSUE THREAD

**Issue by OwnageIsMagic** [VkOpt/VkOpt#339]
на каждый `processLinks` происходит чтение из `localstorage`, которое активно крутит мой ЖД

**Comment by KiberInfinity** [comment]
Вот 
https://github.com/VkOpt/VkOpt/commit/44c05c15fab1f60ae4f703106ca2a2a0f8b02d4d

можно было бы на фоне этого прикрутить и такое, чтоб при изменении опции на одной вкладке она сразу применялась бы и на другой, но я решил не трогать другие вкладки до обновления страницы.

**Comment by OwnageIsMagic** [comment]
получать значение по умолчанию из `onSettings`
