### ISSUE TITLE
Как добавлять модули?

### ISSUE THREAD

**Issue by RblSb** [VkOpt/VkOpt#353]
Полистал вики, мало что понял. Допустим, хочется сделать модуль для изменения элемента в интерфейсе вк, включая галочку на странице настроек вкопта.

Нужно / можно ли создавать отдельный файл и прописывать его в packed_scripts[0].files / packed_scripts[1].files?
Под фреймами подразумеваются окошки вроде тех, которые можно было скрывать при загрузки аудио/видео в старой версии вкопта?
Имеет ли смысл такую мелочь вообще делать модулем? Правку фона как я понял просто внесли куда-то в настройки, не знаю где можно найти эту функцию в коде.

Было бы неплохо увидеть немного более конкретный пример самого модуля, вроде того же изменения фона (пусть там и нужно всего две строчки кода), как он устроен и как подключается, а то объект с кучей пустых функций в ступор вводит, не знаю с чего начинать даже :(

**Comment by RblSb** [comment]
И еще, прикрепите пожалуйста колорпикер и к цвету фона в настройках, белый слишком сливается, но текущий серый все-таки слишком темный, хотелось бы задать что-то вроде #f5f5f5 там.

**Comment by KiberInfinity** [comment]
> Нужно / можно ли создавать отдельный файл и прописывать его в packed_scripts[0].files / packed_scripts[1].files

Можно и так. Кроме этого возможно нужно будет в manifest.json указать в секции web_accessible_resources новый файл.


Или же можешь сделать основу, где всё будет с гитхаба подгружаться с твоего форка.
В background.js
```
ex_loader = {
   type:'internal', // internal|beta|online
```
поменять type с internal на beta или online, и подправить ниже пути внешние на твой форк гитхаба на нужную ветку. Тогда набор подключаемых файлов контролируешь в config.json, и всё это будет тянуться с гитхаба и кэшироваться в локальном хранилище. 
Нажатие Alt+Ctrl+U на странице вк будет зачищать локальное хранилище расширеня и сбрасывать кэш.

**Comment by KiberInfinity** [comment]
Пример плагина со сменой фона на кастомный цвет с просмотром изменений сразу (надо обновиться, т.к в только что пофиксил баг с color_picker'ом тут https://github.com/VkOpt/VkOpt/commit/d5bff92a7e00a4985d57af1c8778021c1f893bb3).

```
window.vkopt = (window.vkopt || {});
vkopt['my_bg'] =  {
   onSettings:{
      vkInterface:{
         custom_bg:{ // Опция с галкой
            title: 'CustomBackground',
            class_toggler: true, // обозначает что при включении автоматически добавляет к тегу <html> класс с именем "vk_custom_bg" ("vk_"+ID_опции)
            sub: { // вложенная опция с выбором цвета
               custom_bg_color:{
                  title: ' ', // тут нам название не нужно
                  color_picker: true
               }
            }
         },         
      }
   },
   css_custom_bg: function(color){ //тут будем генерировать CSS  с нужным цветом
      // Парсим комменты в которых CSS-код лежит
      return vk_lib.get_block_comments(function(){
         /*css:
         .vk_custom_bg body{
            background: #{bg_color};
         }
         .vk_custom_bg .im-page.im-page_classic .im-page--header-chat,
         .vk_custom_bg .im-page.im-page_classic .im-page--header,
         .vk_custom_bg .im-page.im-page_classic .im-page--chat-input
         {
            border-color: #{bg_color};
         }
         */
      }).css.replace(new RegExp("{bg_color}", 'g'), color); // выдрали CSS-код и сразу вшиваем в него цвет
   },   
   css: function(){
      vkopt_defaults.config['custom_bg_color'] = 'F6F6F6'; // пока что костыль подсовывания дефолтного значения, если не редактировать vkopt.js
      // Возвращаем CSS который будет добавлен в страницу при загрузке
      return vkopt.my_bg.css_custom_bg(vkopt.settings.get('custom_bg_color'));
   },
   // А ещё мы хотим сразу просматривать изменения
   onOptionChanged: function(option_id, val, option_data){
      if (option_id == 'custom_bg_color' && vkopt.settings.get('custom_bg')){ // если поменялся цвет и его применение активировано
         // при изменеии опции мы добавляем тег <style>  с обновлённым кодом
         // который будет перекрывать тот, который был добавлен при загрузке страницы
         // если тег существует, то просто обновляем в нём код
         clearTimeout(vkopt.my_bg._chbg_to); // можно и через debounce, а можно и так.
         vkopt.my_bg._chbg_to = setTimeout(function(){
            var code = vkopt.my_bg.css_custom_bg(val); // сгенерили новый css c новым цветом
            var st = ge('vk_custom_bg_preview');
            if (!st)
               vkaddcss(code, 'vk_custom_bg_preview');
            else
               val('vk_custom_bg_preview', code);
         },200)
      }
   } 
}
if (window.vkopt_core_ready) vkopt_core.plugins.delayed_run('my_bg'); // если вкопт уже был запущен, то наш плагин запускаем вручную.

```

**Comment by KiberInfinity** [comment]
скопипастил сюда:
https://github.com/VkOpt/VkOpt/wiki/Примеры-модулей

**Comment by RblSb** [comment]
По поводу class_toggler: true, хтмл-класс в начале страницы нужен просто чтобы хранить галочки настроек? Юзать куки или локал сторадж хуже? И где хранится тогда кастомный цвет фона сообщений сейчас?
И этот плагин для фона страниц сейчас есть в коде в таком варианте, или просто как пример? В примере вижу колорпикер, но на странице настроек его нет, в файле vkopt.js что-то похожее тоже не нашел (последний коммит).

Но в общем спасибо за разъяснения, я так понимаю, проще всего мелкие плагины пихать в конец файла vkopt.js? И еще, можешь подсказать наиболее быстрый способ тестить изменения в расширении? Постоянно коммитить и жать Alt+Ctrl+U как-то ненормально мне кажется.

**Comment by RblSb** [comment]
@KiberInfinity По поводу class_toggler: true, хтмл-класс в начале страницы нужен просто чтобы хранить галочки настроек? Юзать куки или локал сторадж хуже? И где хранится тогда кастомный цвет фона сообщений сейчас?
И этот плагин для фона страниц сейчас есть в коде в таком варианте, или просто как пример? В примере вижу колорпикер, но на странице настроек его нет, в файле vkopt.js что-то похожее тоже не нашел (последний коммит).

Но в общем спасибо за разъяснения, я так понимаю, проще всего мелкие плагины пихать в конец файла vkopt.js? И еще, можешь подсказать наиболее быстрый способ тестить изменения в расширении? Постоянно коммитить и жать Alt+Ctrl+U как-то ненормально мне кажется.

**Comment by KiberInfinity** [comment]
Чисто пример. В вкопте его нет.  Класс нужен чтоб делать стили применение которых видно сразу как только галка будет поставлена

**Comment by KiberInfinity** [comment]
> В примере вижу колорпикер, но на странице настроек его нет

если запустить код плагина с консоли, а потом зайти в настройки - он там появится.

**Comment by KiberInfinity** [comment]
> И еще, можешь подсказать наиболее быстрый способ тестить изменения в расширении?
тогда как есть - добавить в vkopt.js модуль, потом build.bat и обновить страницу вк

**Comment by RblSb** [comment]
@KiberInfinity поправь в примере один аргумент vkopt.settings.get('custom_bg') на 'custom_bg_color'. И откомменть пожалуйста что делают функции ge() и val() там, на будущее.

**Comment by KiberInfinity** [comment]
В примере две опции по факту:
custom_bg - активен ли стиль кастомного цвета фона
custom_bg_color  - выбранный цвет

ge(id) - получение элемента по id
val(elem, new_value || new_innerHTML) - если один аргумент, то возвращает внутреннее содержимое элемента или его значение, если два - то второй аргумент применяется как value элемента, или же как innerHTML.

присвоение напрямую через innerHTML лучше не использовать, т.к потом может получиться так, что многое нужно будет переделывать, чтоб пройти через фильтры для подписи расширения под Firefox
