### ISSUE TITLE
зеркало вк

### ISSUE THREAD

**Issue by OwnageIsMagic** [VkOpt/VkOpt#362]
@Pmmlabs до ввода нового дизайна вёл зеркало вк
https://github.com/Pmmlabs/vk_mirror
что бы более адекватно реагировать на правки вк предлагаю возобновить это начинание
ЗЫ каким деобусификатором вы пользуетесь?
я этим http://www.jsnice.org/

**Comment by KiberInfinity** [comment]
да тут можно без деобфускатора, чисто форматирования достаточно.

**Comment by Pmmlabs** [comment]
Оу, я и забыл про него. Деобфускатора там никакого не было, раньше исходники JS лежали в несжатом виде. Когда ввели новый интерфейс, я подумывал прикрутить туда деобфускатор, но не прикрутил. Возобновить конечно хорошо, и странно, что там прекратилось всё это само обновляться. Хотя нет, не странно. Дело в том, что я разместил этот скрипт на сервере на моем предыдущем месте работы (ну т.к. у меня всегда был к нему доступ и он работал 24/7), а весной я перешел работать в другую компанию а на том сервере видимо что-то случилось с этим репозиторием и он перестал выкачиваться. Мне даже кажется, что выкачивается там до сих пор, только не пушится, там до этого тоже была такая проблема иногда. Как-нибудь зайду туда, посмотрю в чем дело.

**Comment by OwnageIsMagic** [comment]
Вопрос про деобус был чисто житейский. 
Для зеркала ― хоть шланг-формат, главное не менять тулзу потом

**Comment by Pmmlabs** [comment]
юхуу!
![default](https://cloud.githubusercontent.com/assets/2682026/19981298/0e2b2aa8-a20a-11e6-853a-04db7406659c.png)
