### ISSUE TITLE
Ошика при скачивании видео

### ISSUE THREAD

**Issue by RblSb** [VkOpt/VkOpt#371]
При нажатии кнопки скачивания, начинает скачиваться предыдущее видео из плейлиста, а не текущее проигрываемое.

**Comment by KiberInfinity** [comment]
в консоли ошибки какие-то были?

**Comment by RblSb** [comment]
@KiberInfinity не было

**Comment by KiberInfinity** [comment]
А есть ссылка куда-то где можно стабильно это воспроизвести? 
З.Ы. это на версии из репы баг, или на релизе?

**Comment by OwnageIsMagic** [comment]
У меня вообще скачивание видео не работает
(нету кнопки нигде) 
__иногда__ появляется кнопка у видео с ютуба, которая ничего не делает
![(вот тут)](https://cloud.githubusercontent.com/assets/10534634/20578690/90262006-b1d9-11e6-8188-5326f312a361.png)

**Comment by KiberInfinity** [comment]
На релизе не исключаю. И не исключаю что при открытии по прямой ссылке не будет кнопки скачивания.
А так при открытии видео с сайта на версии с гитхаба пахать должно.

**Comment by RblSb** [comment]
@KiberInfinity проверил на последней сборке, все работает корректно. Проглядел коммит на фикс скачивания видео, поэтому поленился обновляться и тестировать снова.

**Comment by RblSb** [comment]
Нет, баг все-таки есть. Один из возможных способов увидеть - открываем первое видео любого плейлиста где больше 2 элементов, из списка этого плейлиста в левом меню выбираем следующий элемент. Пытаемся скачать это самое второе видео - начинает качать третье.
Ну и иногда, если открыть просто ссылку vk.com/video-id, то кнопка скачивания может отсутствовать (видео залитое вк).

**Comment by KiberInfinity** [comment]
Вроде бы подправил ситуацию, когда чужие ссылки могли выдаваться, но надо чекнуть кому-то ещё.
https://github.com/VkOpt/VkOpt/commit/589776ccefc814b3f24fe5c0be64fcb0e1e1b42b
