### ISSUE TITLE
Скачивание музыки в хроме

### ISSUE THREAD

**Issue by OwnageIsMagic** [VkOpt/VkOpt#373]
```html
<a class="audio_act vk_audio_dl_btn vk_audio_acts" ... onmousedown="vkopt.audio.prevent_play();" onclick="vkopt.audio.prevent_play(); return vkDownloadFile(this);" onmouseover="vkopt.audio.btn_over(this);"><div></div></a>
```
```js
function vkDownloadFile(el,ignore) {
   if (!vkbrowser.mozilla || ignore) return true;
...
```
или я смотрю не там?
а ещё в common.js есть замечательная функция `cancelEvent(event)` вместо этого велосипеда

**Comment by KiberInfinity** [comment]
В Firefox нужно блокировать переход по ссылке (успешно предотвратить проигрывание можем и инициировать скачивание), а в хроме не нужно блокировать, т.к нужен переход по ссылке.
Но из-за разрешения перехода по ссылке, обработается и клик по треку, и он начнёт воспроизводиться. Отсюда костыль предотвращающий проигрывание при клике по ссылке.

**Comment by OwnageIsMagic** [comment]
на вкшных кнопках таких костылей не висит, не понимаю зачем он тут
Chromium 57 работает с просто `onclick='return vkDownloadFile(this);'`
FF 52 точно также

**Comment by KiberInfinity** [comment]
У вк не висит костыль потому, что им не нужно всплытие ивента, а для скачивания трека кликом по ссылке этот ивент нужен.
P.S. vkDownloadFile работает только для FF.

**Comment by OwnageIsMagic** [comment]
можешь сам проверить сам проверить в #374 
скачивание работает нормально

**Comment by KiberInfinity** [comment]
Кстати, на форуме было сообщение:
https://vkopt.net/forum/showpost.php?p=71394
про добавление префикса `data:audio/mpeg;charset=utf-8,` к ссылкам, после чего начинает работать атрибут "download".
Если так сделать, то у меня на винде скачивается текстовый файл с ссылкой на трек, но с именем указанным в download-атрибуте. Слабо верю в то, что на маке оно работает по другому.

**Comment by MasterGroosha** [comment]
@KiberInfinity Кстати, скачивание музыки сломалось после очередного обновления раздела музыки (где-то пару недель назад от момента написания этого коммента)

**Comment by KiberInfinity** [comment]
3982c58e0358ef6ada4c05d1e62642102c5965a0
пока далеко не всё по аудио исправлено. нет битрейта, нет уменьшения промежутков, запрос ссылки идёт только на наведенный трек, к соседним четырём трекам ссылки не подгружаются как раньше

**Comment by MasterGroosha** [comment]
@KiberInfinity спасибо огромное!
