### ISSUE TITLE
Ох уж этот MBAM

### ISSUE THREAD

**Issue by bykidi** [VkOpt/VkOpt#376]
![default](https://cloud.githubusercontent.com/assets/1337953/21720579/06c790f0-d435-11e6-866e-499d09600da1.png)
Что vkopt им сделал такого? Антивирус отличный, но вот анти-бэд-вебсайт капитально блочит половину интернета.

**Comment by EgoAkk** [comment]
> но вот анти-бэд-вебсайт капитально блочит половину интернета
Зачем тогда таким г.. пользоватся? Я им зарепортил.
Но Вы как пользователь, лучше бы сами зарепортили в поддержку о ложном срабатывании.

**Comment by bykidi** [comment]
Отличная эвристика и база антивируса как плюс перекрывает все минусы, такие как, например, невозможность установки только антивируса.

**Comment by EgoAkk** [comment]
Скорее всего это из-за того, что сайт переехал на новый IP. Видимо он ранее попал в базу заблокированных. 

Суппорт Malwarebytes ответил, что передал инфу об ошибке департаменту антифируса, они будут разбираться.

**Comment by bykidi** [comment]
Спасибо, будем ждать обновку.

**Comment by EgoAkk** [comment]
Сообщили что IP удалили из базы и через пару часов она обновится у юзеров и на сайт можно будет зайти
