### ISSUE TITLE
Не всегда загружаются все скрипты

### ISSUE THREAD

**Issue by OwnageIsMagic** [VkOpt/VkOpt#379]
не всегда загружается `vkopt.js`
обновление страниицы спасает
баг древний
![image](https://cloud.githubusercontent.com/assets/10534634/22077582/c5ca9daa-ddc5-11e6-8367-476ae0c4211f.png)
в консоли браузера ошибок нет
![image](https://cloud.githubusercontent.com/assets/10534634/22077574/bd6a35a8-ddc5-11e6-9d0b-e3e80b7cb6ac.png)

**Comment by KiberInfinity** [comment]
хм. т.е vk_lib.js загружается, а vkopt.js даже не подключен к странице? о_О

**Comment by OwnageIsMagic** [comment]
Такие дела
В v2 был баг немного схожий баг
Всё подключалось, но надо было ручками(из закладки) вызвать VkOptInit() 
Но тут даже и следа нет
