### ISSUE TITLE
[Chrome] Нет кнопки "скачать" у последней аудиозаписи в посте

### ISSUE THREAD

**Issue by MasterGroosha** [VkOpt/VkOpt#381]
Неоднократно замечал, думал сначала, что это баг ВК. 
У меня на двух системах (Windows 10 и Kubuntu 16.04) воспроизводится всегда. У последней аудиозаписи нет кнопки "Скачать", вместо неё бесконечная иконка загрузки (3 горизонтальные точки). В консоли разработчика ничего не вижу.
![image](https://cloud.githubusercontent.com/assets/2780044/22331257/8cd63c72-e3db-11e6-916b-5aa29c8496a7.png)

**Comment by localhoster** [comment]
Репродуцируется и в Windows 7. Воркэраунд - запрашивать информацию о размере вручную, начиная с конца, тогда не появится та кнопка загрузки, что будет вызвана девятой по счету. Может какая-то защита ВКшного апи от массового скачивания?

**Comment by KiberInfinity** [comment]
Fixed: d7587d859599fc33bcca565ba299a3db5618aead
