### ISSUE TITLE
Блокировка скачивания аудиозаписей

### ISSUE THREAD

**Issue by RblSb** [VkOpt/VkOpt#384]
При попытке скачать аудиозапись с помощью вкопта загружается аудио заглушка с просьбой использовать оф. приложения.

**Comment by OwnageIsMagic** [comment]
Offtopic
__Уже предславляю тред в котором будем искать CORS проки__

**Comment by Aleksandrln** [comment]
В файле https://vk.com/js/al/audioplayer.js лежит метод
`function e(t) {
            if (~t.indexOf("audio_api_unavailable")) {
                var i = t.split("?extra=")[1].split("#")
                  , e = o(i[1]);
                if (i = o(i[0]),
                !e || !i)
                    return t;
                e = e.split(String.fromCharCode(9));
                for (var a, r, l = e.length; l--; ) {
                    if (r = e[l].split(String.fromCharCode(11)),
                    a = r.splice(0, 1, i)[0],
                    !s[a])
                        return t;
                    i = s[a].apply(null, r)
                }
                if (i && "http" === i.substr(0, 4))
                    return i
            }
            return t
        }`
превращающий заглушку [https://vk.com/mp3/audio_api_unavailable.mp3](https://vk.com/mp3/audio_api_unavailable.mp3?extra=AhrOChm6lY9WC3yOlNzRlM1L…O9pDefUog45veu2rJf3CePYtMvozhmXCO1dnY1cs3K1qKfYrhbVmLvMmtnUnZzXmvz2ma#DGL2)
в корректную ссылку [https://psv4.vk.me/c613326/u144427465/audios/cd48ab9d22f7.mp3](https://psv4.vk.me/c613326/u144427465/audios/cd48ab9d22f7.mp3?extra=C9vSbta…dLPBFp_Bdon3wu2To0p8bHsOOtAn8n9TE6F1wpJrNeNds1sMC7-BKy5BArDpo2Uf13n76q1Vv0)

**Comment by KiberInfinity** [comment]
https://github.com/VkOpt/VkOpt/commit/4487f1a5d38997988765e386deabf568d537c835
