### ISSUE TITLE
патчинг imn.js

### ISSUE THREAD

**Issue by OwnageIsMagic** [VkOpt/VkOpt#391]
Есть предложения?

**Comment by KiberInfinity** [comment]
В теории как-то так:
Выкачивать его аяксом периодически, чтоб был его кэш. Модифицировать его.
По событию подключения скрипта onLibFiles - эвалить модифицированную версию из кэша. 
При загрузке же страницы и наличии скрипта нужно дожидаться инициализации родного модуля, проводить его деинициализацию, и запускать модифицированную версию.

**Comment by OwnageIsMagic** [comment]
Тогда может лучше просто патчить его прямо в хроме?

**Comment by Kesantielu** [comment]
Я вот так пока что и не допер, как с ним работать. Получается, он экспортирует массив анонимных функций.

**Comment by OwnageIsMagic** [comment]
Это обычный собранный webpack проект. На самом верху там анонимная функция загрузчик модулей и там же ей при вызове передаётся список модулей.

**Comment by Kesantielu** [comment]
А как ВК потом его использует?

**Comment by OwnageIsMagic** [comment]
https://github.com/Pmmlabs/vk_mirror2/blob/beeb86f/vk.com/js/al/imn.js#L10993
экспортируется функция инициализации
и при преходе на vk.com/im вызывается
а может ещё где-то

**Comment by OwnageIsMagic** [comment]
Крч
Надо сделать хук в `XMLHttpRequest.prototype.send` и всё будет ок

**Comment by KiberInfinity** [comment]
Если про перехват аяксовых запросов, то обработчики есть:
```javascript

    onRequestQuery:       function(url, query, options){},      /* вызывается перед выполнением ajax.post метода.
                                                                   Если функция вернёт false, то запрос выполнен не будет. */
    onResponseAnswer:     function(answer,url,params){},        /* answer - массив, изменять только его элементы */
    
```

**Comment by OwnageIsMagic** [comment]
Нужен не аякс а подключение к лонг полл серверу
Этот модуль сам создаёт подключения через xhr
А создавать ещё одно своё не хочется

**Comment by OwnageIsMagic** [comment]
В первую очередь для оповещений о наборе сообщения

**Comment by KiberInfinity** [comment]
notifier.js

инжект можно сюда:
FastChat.imFeeds
Notifier.lcRecv


или же вообще пойти нормальным путём и подписаться на сообщения от чата:
`Notifier.addRecvClbk("fastchat", 'vkopt_fastchat_handler', vkopt.log, true);`

**Comment by OwnageIsMagic** [comment]
ничего не приходит в консоль

**Comment by KiberInfinity** [comment]
>ничего не приходит в консоль

а ты пробовал с другого аккаунта начинать печатать себе сообщение?

**Comment by OwnageIsMagic** [comment]
мне писали из беседы

**Comment by KiberInfinity** [comment]
Спецом проверил сейчас. Сразу начала консоль загаживаться ивентами, как только выполнил из консоли код.

**Comment by OwnageIsMagic** [comment]
![image](https://cloud.githubusercontent.com/assets/10534634/26333135/1250e3d2-3f64-11e7-9460-cceaec2c15ee.png)

**Comment by OwnageIsMagic** [comment]
если включить дебаг в нотифаере то спам идёт, но в нём ничего интересного

**Comment by KiberInfinity** [comment]
Вот пример ивента от чата о наборе сообщения:
![](http://s3.micp.ru/TDdCC.png)

**Comment by OwnageIsMagic** [comment]
Я разобрался
Эвенты идут только когда больше одной вкладки

**Comment by OwnageIsMagic** [comment]
Что собственно логично
![image](https://cloud.githubusercontent.com/assets/10534634/26449806/026e319a-415d-11e7-95b7-1030d76fd885.png)
`lc` stands for `local connection`

**Comment by KiberInfinity** [comment]
Оно по всем открытым вкладкам рассылает ивент.
