### ISSUE TITLE
Отказ работы после обновления

### ISSUE THREAD

**Issue by RblSb** [VkOpt/VkOpt#392]
Есть идеи по фиксу? По большей части переделывали музыку. Вроде где-то был репозиторий с сейвом фронтенд-части вк.

**Comment by DmitriyTSt** [comment]
Что-то не так с функцией

function isNewVk(){return typeof prepareAudioLayer != 'undefined'}

Запуск на ней вылетал
Если убрать из vkopt_core.init() эту проверку, то все работает и плагин запускается

**Comment by DmitriyTSt** [comment]
Можно в релизе тоже просто убрать эту проверку наверное и выпустить обновление. А то по запросу "вкопт" в вк у людей массовые волнения, что плагин не работает.

**Comment by RblSb** [comment]
@DmitriyTSt похоже проверка на новый диз вк происходила по плееру, так как функция возвращает false - то ничего и не загружалось дальше. Сейчас эта проверка уже не имеет смысла. Да, спасибо, теперь все номр. Только вот запостить фикс вк мы не можем.

**Comment by DmitriyTSt** [comment]
Почему?

**Comment by RblSb** [comment]
@DmitriyTSt я имею ввиду оф. группу вкопта. Хотя, наверно кто-то кроме Михаила имеет доступ к стене. В общем буду ждать.

**Comment by DmitriyTSt** [comment]
И webstore хрома тоже только у него?
Печально

**Comment by OwnageIsMagic** [comment]
Толку от того что написать на стене? 
Юзверы же не полезут в папку профиля коментить строещё. 
Нужен доступ к профилям в сторах аддонов что бы выложить новю версию, т.к. эта проверка происходит ещё до загрузки хотфиксов. 
А это точнно только у него есть

**Comment by OwnageIsMagic** [comment]
Тут можно под шумок свергнуть главного мейнтейнера под предлогом медленной реакции на важные события проекта, да и PR уже штуки 3 висят просто 😈 
(Ыыы)

**Comment by DmitriyTSt** [comment]
@OwnageIsMagic Ну например мой друг разбирается в программировании, и я ему скинул просто исходники с правкой, и он поставил сам.
