### ISSUE TITLE
Keep online

### ISSUE THREAD

**Issue by solomax2014** [VkOpt/VkOpt#400]
В связи с обновлением ВК, связанным с изменением времени "удержания" онлайна (15 -> 5 минут), предлагаю добавить функцию поддержания онлайна (на время работы вкладок с ВК). Думаю, что такая функция может быть полезна, т.к. постоянно уходить в оффлайн из-за неактивности, хотя сидишь с открытой вкладкой ВК, как-то не очень приятно.

**Comment by EgoAkk** [comment]
Такая функция раньше была во ВкОпте. 
Но на самом деле оно не будет правильно работать с современными браузерами. Браузеры сейчас стараются глушить неактивные вкладки и со временем эта функция отвалится, если вкладка долго не будет открываться. 

PS: давайте предложения по функционалу присылать на форум в соответствующую тему. А тут обсуждения оставим для решения технических вопросов в коде проекта.
