### ISSUE TITLE
включенный обход away.php ломает кириллическую кодировку ссылок на Google поиск

### ISSUE THREAD

**Issue by Kyogre** [VkOpt/VkOpt#403]
при включенном обходе away.php ссылки вида "https://www.google.ru/search?q=%D0%B2%D0%BA%D0%BE%D0%BF%D1%82&ie=utf-8&oe=utf-8&gws_rd=cr&ei=hzZGWYPmOMnUwQL-q42YBg", открытые например из диалога, деградируют в "https://www.google.ru/search?q=%E2%EA%EE%EF%F2&ie=utf-8&oe=utf-8&gws_rd=cr&ei=hzZGWYPmOMnUwQL-q42YBg", т.е. вместо введенного запроса гугл начинает искать знаки вопроса "?????"

**Comment by KiberInfinity** [comment]
255c8f568ea578331b1c5b7e596df977bda572be

**Comment by KiberInfinity** [comment]
ещё одну правку залил. 
вот такие ссылки я пока что игнорирую:
```
/away.php?to=https%3A%2F%2F%EF%F0%E0%E7%E4%ED%E8%EA%E8-%F0%FF%E7%E0%ED%E8.%F0%F4%2F2017-08-18-2&post=177665937_1672&cc_key=
```
