### ISSUE TITLE
Дополнительные действия при картинках

### ISSUE THREAD

**Issue by stsyn** [VkOpt/VkOpt#404]
Не помню точно, когда именно вылезло, вроде на прошлой неделе

1) Меню сдвинуто и низ выглядит косо
![image](https://pp.userapi.com/c637930/v637930658/4ee66/ShURhBsTwio.jpg)

2) При каждом новом наведении пункты меню продолжают добавляться
![image](https://pp.userapi.com/c637930/v637930658/4ee5c/1Gxv43nz4Vc.jpg)

Включение/отключение юзерстилей не влияет на баг

**Comment by KiberInfinity** [comment]
8fb8c13a8d93bb97b6eeb033cb44942b9d87e9c5
