### ISSUE TITLE
Комментарий не от имени группы

### ISSUE THREAD

**Issue by fleytman** [VkOpt/VkOpt#406]
В ВК вновь ввели "полезную фичу" - https://vk.com/wall-32295218_418053
Теперь приходится на каждом комменте в своём сообществе переключать от чьего имени отвечать. Хотелось бы чтобы запоминалось от чьего имени был последний коммент. Или хотя бы просто коммент от своего имени, а не имени группы по умолчанию

**Comment by EgoAkk** [comment]
Присылайте предложения на форуме.

**Comment by fleytman** [comment]
Ок. Хотя Лэйблы в issues не просто так. Фич реквест на багтреке позволяет без поиска по форумам предложить не дублирующую фичу.

**Comment by OwnageIsMagic** [comment]
Легаси
90%пишут на форум
А тут ещё и всё на английском

**Comment by fleytman** [comment]
Да я сам на форуме что-то писал когда-то. Но вроде с 2014 года гитхаб репозиторий появился.

Всё-таки это профессиональный инструмент для таких вещей. Очень быстро можно расклеить лэйблы с каким приоритетом, делаешь/не делаешь, баг/не баг, не баг, фича и т.д. 
С форумов обычно переносят фич реквесты и баги, чтобы не потерялись.

> А тут ещё и всё на английском

Хз, на гитхабе максимально дружелюбный интерфейс, слабо верю, что у кого-то проблема сюда писать.

**Comment by OwnageIsMagic** [comment]
> максимальнодружелюбный интерфейс

Никак не поможет с тремя экранами регистрации
<img witdth="360" height="640" src="https://user-images.githubusercontent.com/10534634/28240228-1978430c-6986-11e7-8306-6219f71e0c48.png" />

**Comment by fleytman** [comment]
@OwnageIsMagic, только что проверил. Если перевести страницу гугл транслэйтом, то вообще проблем, что куда вводить нет. На второй шаг переводит после первого, и там по сути ничего менять не надо. 

Самое главное, на гитхабе нет дебильных полей "подтвердите пароль", "подтвердите email" и "секретный вопрос". Учитывая, что люди сейчас могут зарегаться на paypal, где регистрация конченная, не представляю у кого возникнет трудность с гитхабом.

**Comment by OwnageIsMagic** [comment]
В автобусе сидел с парнем лет 25
он открыл какой-то сайт на английском, ему хром предложил перевести
он сразу же нажал `нет`, полистал его секунд 10 и в пол голоса сказал  `нет бы сделалать на русском`

**Comment by localhoster** [comment]
Я бы не стал серьёзно ожидать толкового фич-реквеста или багрепорта от человека, который даже на гитхабе зарегаться не может.
