### ISSUE TITLE
Не работает скачивание музыки

### ISSUE THREAD

**Issue by kozintsev** [VkOpt/VkOpt#407]
Не работает скачивание музыки.
Проблема только у меня или есть ещё прецеденты?

**Comment by localhoster** [comment]
Подтверждаю, не работает с 6 июля в версиях 3.0.2 и теперь 3.0.3 на Chrome 59

**Comment by kozintsev** [comment]
Firefox Developer Edition 55b09 тоже не работает

**Comment by EgoAkk** [comment]
Это известная проблема. Работа по восстановлению функционала из раздела музыки ведется. Ждите обновления
