### ISSUE TITLE
При сохранении сообщений не все emoji сохраняются корректно

### ISSUE THREAD

**Issue by SuperPers16** [VkOpt/VkOpt#408]
Во время использования приложения, я заметил, что не все emoji видны в сохранённом HTML-файле. Я думал они тупо не сохраняются, но решил заглянуть в код и обнаружил там корявые ссылки на некоторые emoji.

Данный код показывается **корректно**:
`<img class="emoji" alt="😂" src="http://vk.com/images/emoji/D83DDE02.png">`

А вот код emoji, которые не показываются:
`<img src="http://vk.com/images/blank.gif" emoji="D83DDE09" alt="😉" class="emoji_css" style="background-position: 0px -34px;">`

Я думал, может какие-то смайлы просто не поддерживают сохранение. А нет, если переписать код так, всё работает нормально:
`<img class="emoji" alt="😉" src="http://vk.com/images/emoji/D83DDE09.png">`

Менять все строки с корявыми ссылками в коде как-то не прикольно, особенно, если переписка длинная. Так что прошу **обратить на это внимание и исправить этот баг!**

А так расширение очень удобное, спасибо разработчикам!

**Comment by KiberInfinity** [comment]
@SuperPers16 
Для вставки смайлов используются родные обработчики контакта.
Часть смайлов использует вместо ссылок на картинки общий спрайт с популярными emoji. Для таких указывается class="emoji_css"
если к странице подключен /css/al/common.css, то такие смайлы должны отображаться, т.к в этом стиле описан спрайт для них
![](http://vk.com/images/im_emoji.png)

возможно у вас подключение этого css блокирует что-то?

**Comment by SuperPers16** [comment]
Всё разобрался, спасибо.

Дело было в том, что строка, которая подключала /css/al/common.css к странице почему-то изначально была закомментирована, я не знаю почему:
`<!--<link rel="stylesheet" type="text/css" href="http://vk.com/css/al/common.css" />-->`

**Comment by KiberInfinity** [comment]
@SuperPers16 
fcd3b1b918e28233d20b18bc98f4495dddfdabd0
добавил CSS для emoji в шаблон переписки. должно работать без подключения common.css

**Comment by SuperPers16** [comment]
Неа, либо я туплю, либо не работает. Показывает пустые картинки, вместо emoji. В консоли ошибка:
Failed to load resource: net::ERR_FILE_NOT_FOUND im_emoji.png

**Comment by KiberInfinity** [comment]
@SuperPers16  это я домен забыл добавить.
фикс вроде бы
d6c54159851921c034344aadebae2383d1e3c41b

**Comment by SuperPers16** [comment]
@KiberInfinity
Точно, теперь работает и без common.css, спасибо)
