### ISSUE TITLE
шрифт битрейта и размера аудиофайлов

### ISSUE THREAD

**Issue by jatows** [VkOpt/VkOpt#409]
День добрый, огромное спасибо за вновь вернувшуюся возможность скачивать аудиозаписи. Там чуть шрифт увеличьте отображения битрейта и размера файлов, можно даже такой же как и самих названий песен. Они теперь в две строки ведь.
Это не критично, но слегка не комфортно приглядываться. Как-нибудь с новым релизом подправьте пожалуйста. Спасибо.

**Comment by KiberInfinity** [comment]
b22fb9ca19ca394b93f609a330aa214830982f05
