### ISSUE TITLE
поплыли аудио кнопки

### ISSUE THREAD

**Issue by OwnageIsMagic** [VkOpt/VkOpt#410]
![image](https://user-images.githubusercontent.com/10534634/29302727-55c750fc-818f-11e7-9834-2d910dc22179.png)
Я ничего не делал оно само!

**Comment by KiberInfinity** [comment]
Это в каком разделе аудио?

**Comment by OwnageIsMagic** [comment]
Во всех audio row

**Comment by OwnageIsMagic** [comment]
Лента
![image](https://user-images.githubusercontent.com/10534634/29325372-07bda558-81f0-11e7-849b-6471e822c03e.png)
Мои аудио
![image](https://user-images.githubusercontent.com/10534634/29325400-289e8b70-81f0-11e7-9d61-951e1c27f507.png)
Самый первый скрин - плеер из шапки
Я думаю это связано с `display: inline-block` и то что остальные кнопки это `<button>` а наша `<div>`
![image](https://user-images.githubusercontent.com/10534634/29325803-b808c590-81f1-11e7-8b47-b5c7efd69d9f.png)

**Comment by KiberInfinity** [comment]
Надо было сразу говорить что под FF такая трабла)

**Comment by KiberInfinity** [comment]
f96a4b5d94802c72fdf5399de11f1c7fbea1c73c

**Comment by OwnageIsMagic** [comment]
Ну дебагер явно не хромированный на скрине
Я не тестил, но закрою

**Comment by RblSb** [comment]
Появилось снова
![default](https://user-images.githubusercontent.com/8753432/30995603-1e1edfb4-a4c4-11e7-9879-4ad6a64cbf2a.png)

**Comment by OwnageIsMagic** [comment]
Я не тестил, но открою

**Comment by KiberInfinity** [comment]
@RblSb  на каком браузере?

**Comment by RblSb** [comment]
@KiberInfinity FF 56

**Comment by RblSb** [comment]
Забыл сказать, это только в всплывающем меню плеера из шапки

**Comment by RblSb** [comment]
Причина в кнопке пропуска аудио, если ее отключить - все нормально. Кстати, сама кнопка более не нужна, как я понимаю, раз вк добавил свою кнопку удаления аудио из плейлиста?

**Comment by KiberInfinity** [comment]
@RblSb не факт, если только переделать родную кнопку, чтоб она сразу не удаляла окончательно, и была бы возможность вернуть трек обратно.

**Comment by KiberInfinity** [comment]
6c0f3d28044e2ed2d5bbaca750929996541b3a62
вроде бы фикс
![](http://kisshot.ru/imgs/77UCG2.png)
![](http://kisshot.ru/imgs/77UFIJ.png)
