### ISSUE TITLE
Баг при повтормном клике на "Написать сообщение" в группе

### ISSUE THREAD

**Issue by BaHeK1994** [VkOpt/VkOpt#411]
В группе при первом нажатии "Написать сообщение" вылезает диалоговое окно, как и должно быть, но если это окно закрыть и еще раз нажать на кнопку "Написать сообщение", то происходит редирект на страницу: https://vk.com/im.
Без vkopt проблем нет. В консоле ошибок нет.
Возможно, проблема в этих смайлах:
![iz6s](https://user-images.githubusercontent.com/18642618/29601700-8a11fdb0-87e5-11e7-8afc-179af7646f24.png)

Они появляются, даже если отключена эта функция:
![u471](https://user-images.githubusercontent.com/18642618/29601704-8e374be8-87e5-11e7-873d-bfee57fc006f.png)

Проверял наличие бага в 2-ух браузерах: Firefox 55.0.2 и Chrome 60.0.3112.90
ОС: Ubuntu 16.04

**Comment by RblSb** [comment]
Предлагаю выпилить их добавление в всплывающие окна, не хочу их там поддерживать.

**Comment by KiberInfinity** [comment]
e1a6f8fa361f3a211948d21f15e04aa2ccd6345a
Фикс
