### ISSUE TITLE
Уменьшение промежутков между аудио (баг)

### ISSUE THREAD

**Issue by DmitriyTSt** [VkOpt/VkOpt#417]
Прикрепление аудио, chrome

![image](https://user-images.githubusercontent.com/12156501/31020780-fb352536-a544-11e7-951a-0a8f50808619.png)

**Comment by KiberInfinity** [comment]
078c38f7a1e43109ef654978e8a068f15b9678a3

![](http://kisshot.ru/imgs/77U2A7.png)
