### ISSUE TITLE
Firefox 57+

### ISSUE THREAD

**Issue by ForumLiker** [VkOpt/VkOpt#419]
Будет ли поддержка браузера Firefox 57? Уже совсем скоро состоится его релиз

**Comment by bykidi** [comment]
компиль через _winrar_firefox_webext_pack.bat
всё работает (косяков пока не замечал)

**Comment by ForumLiker** [comment]
Можешь готовый .xpi скинуть?

**Comment by bykidi** [comment]
ftp.goodgame.by в корне

**Comment by ForumLiker** [comment]
Так он не подписанный. Подписать никак?

**Comment by bykidi** [comment]
зачем, если можно в about:config xpinstall.signatures.required изменить на false?

**Comment by OwnageIsMagic** [comment]
Ставь хромовое crx и всё ок

**Comment by ForumLiker** [comment]
@bykidi , дождусь лучше релиза, пусть добавят на сайт дополнений. все равно функционала очень мало.
@OwnageIsMagic а что firefox уже вдруг научился устанавливать хромовские crx? Глупо, да и не особо нужно)

**Comment by OwnageIsMagic** [comment]
Теперь аддоны для хрома и фф это почти одно и тоже
И это не глупо и нужно что бы писать сразу под все браузеры единый код

**Comment by ForumLiker** [comment]
ну да..свалить все в одну яму...

**Comment by Scvairy** [comment]
Думаю, хватило бы добавить ссылочку https://vkopt.net/upd/vkopt-3.0.4.4-fx.xpi вот сюда: https://vkopt.net/download/

**Comment by ForumLiker** [comment]
@Scvairy Отлично! Файл установился без проблем. Спасибо. Работает. Только вручную, через ссылку не хочет.

**Comment by KiberInfinity** [comment]
@ForumLiker , @Scvairy  
выложенная ссылка - ссылка на тестовый билд. В нём нет ссылки на манифест автообновления. Т.е установленный по этой ссылке вкопт не обновится в будущем автоматически на новую версию.

**Comment by Scvairy** [comment]
@KiberInfinity спасибо, что предупредил. А нет такой ссылки на билд с ссылкой на автообновления в манифесте? 🤔

**Comment by ForumLiker** [comment]
А откуда был собранный этот тестовый билд?

**Comment by OwnageIsMagic** [comment]
Собран, но не подписан мозилой

**Comment by MasterGroosha** [comment]
Есть какие-нибудь новости? В 60.0.1 даже с отключенной проверкой подписи не хочет ставиться, т.к. "не подтверждено"

**Comment by KiberInfinity** [comment]
@MasterGroosha  
тут 
https://github.com/VkOpt/VkOpt/releases 
файл оканчивающийся на `-fx.xpi` - подписанная версия.

если же нужно в фф поставить распакованную сборку, то только через `about:debugging`, и то до перезапуска фаерфокса

**Comment by MasterGroosha** [comment]
@KiberInfinity

Спасибо!
