### ISSUE TITLE
Событие onLocation

### ISSUE THREAD

**Issue by RblSb** [VkOpt/VkOpt#421]
Похоже оно срабатывает только при переходе по ссылке "Моя Страница", на остальные разделы и прочее реакции больше нет. В частности думаю из-за этого ломается кастомная форма ввода в сообщениях (эмодзибар/высота поля ввода). То есть если обновить страницу с включенными опциями в диалоге, то они появятся, но после пары переходов исчезнут. Хотя, может это только у меня в FF58, отпишитесь как у вас =)

**Comment by KiberInfinity** [comment]
Скорей всего из-за обновы вк. Я ещё подробно не смотрел

**Comment by RblSb** [comment]
Теперь все отлично, спасибо!
