### ISSUE TITLE
Некорректное сохранение переписки с группой

### ISSUE THREAD

**Issue by BaHeK1994** [VkOpt/VkOpt#424]
![screenshot](https://user-images.githubusercontent.com/18642618/35481085-a80a38ea-042d-11e8-9b71-cf2dd5d9d409.png)
1) ссылка подставляется vk.com/idXXX, вместо vk.com/clubXXX
2) при репосте некорректно получается информация, нужно обращаться к groupById

**Comment by KiberInfinity** [comment]
@BaHeK1994  ee20bd51a269c1e88538c993c9f3ea4d5f73c23f
