### ISSUE TITLE
Прошу поделиться опытом.

### ISSUE THREAD

**Issue by aq1** [VkOpt/VkOpt#425]
Пишу свое дополнение для браузера для работы с ВК. Хочу проводить манипуляции с текстом сообщения до его отправки (добавлять, заменять слова, например). Но никак не могу перехватить управление у вк ни по нажатию, ни по клику на кнопку отправки сообщения. Я могу поставить event listener, но он сработает уже после отправки сообщения. Можно ли как-то перехватить событие до отправки?

**Comment by OwnageIsMagic** [comment]
Можно 
Куда листнер ставишь?

**Comment by aq1** [comment]
На клавиатуру на document. А на нажатие кнопки еще не пробовал.

**Comment by aq1** [comment]
Блин, я вижу прямо в readme 

```    onImSend:             function(query){},                    /* вызывается перед отправкой личного сообщения.
                                                                   Если функция вернёт false, то сообщение не отправится. */```

Сейчас посмотрю эту функцию и уверен там будет ответ на мой вопрос.

**Comment by aq1** [comment]
Не, не работает, потому что vkopt.im = undefined. Так что видимо нет такого функционала.

**Comment by OwnageIsMagic** [comment]
А вы интересный молодой человек
https://github.com/VkOpt/VkOpt/blob/master/source/vkopt.js#L278
И функционал - это что-то из математики

**Comment by aq1** [comment]
Ну и что это за строчка? Я ее видел. vkopt_core.plugins.call_modules('onImSend', query) возвращает пустой объект. Вдобавок, как я скахал vkopt.im неопределено, нету его. Плюс где этот метот onImSend вообще расположен? Его нет в репозитории, по крайней мере я не нашел.

**Comment by OwnageIsMagic** [comment]
Как не трудно догадаться из приведённой тобой справки ˋonImSend` это событие, а не метод
Дабы не утруждать молодой ум путешествием вверх по стеку вызовов сразу приведу точку входа для него https://github.com/VkOpt/VkOpt/blob/master/source/vkopt.js#L389
Дополнительное очко грифиндору если скажешь  откуда взял ˋvkopt.im ˋ

**Comment by aq1** [comment]
Мда, вот это у тебя чсв, дядя.

**Comment by KiberInfinity** [comment]
@aq1 
Вот пример модуля для vkopt'а выводящий в консоль поля из запроса отправки сообщения.
Можно поставить через TamperMonkey, или же запустить из консоли.
```javascript
window.vkopt = (window.vkopt || {});
vkopt['im_test'] = {
   onImSend: function(query){
     console.log('OnIMSend: ', query)
   }
}
```

Если интересуют потроха - модифицируется код метода из либы вк `ajax.post`, благодаря чему можно перехватить почти любой запрос из кода вк использующий этот метод. Там же происходит перехват запроса на `al_im.php` у которого в теле есть `act:a_send`

**Comment by aq1** [comment]
@KiberInfinity Спасибо за ответ.
Да, интересует именно этот момент патчинга функции. Потому что я взял этот объект Inj, который как раз это и делает и пытался с ним поэкспериментировать. В результате, видимо нарушается CSP и контакт не отправляет сообщения и ругается `Error: Permission denied to access object`.

**Comment by KiberInfinity** [comment]
@aq1 
CSP нарушаться не должен. ошибка скорей всего из-за чего-то другого.
Если не нужны экзотические преобразования кода исходного метода, можно просто навесить обработчик выполняющийся до вызова оригинального метода:
```javascript
Inj.Start('ajax.post',function(url, data, options){
	console.log('AJAX HOOK: ', this, url, data, options);
    // this.prevent = true; // так выглядит блокировка вызова исходного метода ajax.post
});
```

**Comment by aq1** [comment]
Да, я так и делал.
Спасибо, буду разбираться поглубже в этом вопросе.
