### ISSUE TITLE
Не работает сохранение историй в Firefox

### ISSUE THREAD

**Issue by vityafx** [VkOpt/VkOpt#427]
Работает в chromium, но не работает в firefox. Ставил с оф. сайта. Firefox 59.0.2 64 bit (ubuntu). Ребутал браузер после установки, обновлял страницу, все время висит 0% при сохранении.

**Comment by KiberInfinity** [comment]
@vityafx  Это при сохранении чата, переписки с пользователем, или диалога с группой? 
Ошибка на последних коммитах сохраняется, или ошибки относительно релиза?

**Comment by vityafx** [comment]
При сохранении переписки с пользователем в диалоге. Ошибки относительно плагина на оф.сайте.

**Comment by KiberInfinity** [comment]
@vityafx  пока что не удалось воспроизвести под виндой проблему. В консоли страницы какие-нибудь ошибки появляются после нажатия на кнопку сохранения переписки?

**Comment by vityafx** [comment]
@KiberInfinity завтра гляну :)
