### ISSUE TITLE
https://github.com/VkOpt/VkOpt/blob/a140b54f77467f8f4fc8e79d1cbea44a8dd7b67d/background.js#L124

### ISSUE THREAD

**Issue by Ruslan26091990** [VkOpt/VkOpt#439]
b.com/VkOpt/VkOpt/blob/cbd5d4d69cc6e21f5c075410b2d03cb2ad8ff7e0/content_script.js#L194

**Comment by Ruslan26091990** [comment]
победить . postMessage ({response : data, sub : sub}, " * " );

**Comment by Ruslan26091990** [comment]
победить . postMessage ({response : data, sub : sub}, " * " );

**Comment by SGmuwa** [comment]
Мне, как наблюдателю, не понятно, что Вы хотите сделать. Но мне кажется, Вы хотите внести изменения в код. Возможно, Вам стоит сделать Fork этого репозитория, внести свои изменения, провести испытания Вашего изменения, и совершить Pull request в конечный репозиторий.
Тем не менее,
1. при желании **администрации** репозитория,
2. и при условии, что **она** поймёт Ваш Issues,
3. и если Ваше предложение действительно следует конечной цели репозитория,
то **она** обойдёт эти официальности.

**Comment by KiberInfinity** [comment]
Я тоже не понял в чем суть проблемы и что требуется в итоге.
