### ISSUE TITLE
Диалоговое окно flash player

### ISSUE THREAD

**Issue by AscendeSuperius** [VkOpt/VkOpt#441]
При попытке применить ретушь во второй раз всплывает диалоговое окно "установить flash player". Добавьте кнопку "update" и туда, пожалуйста!

**Comment by KiberInfinity** [comment]
https://github.com/VkOpt/VkOpt/commit/0c6a8e9aa11f678ec2158012ac1bf8fb882ddeda
Теперь фоторедактор открывается даже при отсутствии флеша
