### ISSUE TITLE
Аудиозаписи не скачиваются

### ISSUE THREAD

**Issue by roman412** [VkOpt/VkOpt#445]
Отвалилось скачивание аудио. При наведении и нажатии на иконку ⇩ проискодит анимация загрузки, в консоль выводится какой-то объект (вида _Arguments(3) [div.audio_row.audio_row_with_cover._audio_row._audio_row_2000431740_456241415.audio_can_add.audio_ro…, {…}, Array(20), callee: ƒ, Symbol(Symbol.iterator): ƒ]_), но аудио не скачивается.

- Google Chrome Version 69.0.3497.100 (Official Build) (64-bit)
- VkOpt 3.0.6.3

**Comment by KiberInfinity** [comment]
Коммиты с исправлениями уже пару дней как в репозитории

**Comment by roman412** [comment]
Я не разбирался в архитектуре vkopt. Этот e3d32bfc3d0d77bbcc24e4f2489731bff04e8317 ?

**Comment by KiberInfinity** [comment]
Конкретно по скачиванию - да.

**Comment by roman412** [comment]
Ага, заработало. Благодарю!
