### ISSUE TITLE
Сломалось скачивание музыки (HTTP Live Streaming)

### ISSUE THREAD

**Issue by gugglegum** [VkOpt/VkOpt#452]
Похоже, что это связано с тем, что теперь MP3 не загружаются одним цельным фрагментом, а загружаются маленькими частями обычно по 128 КБ. При этом используется библиотека hls.js. Все существующие расширения теперь не работают и альтернативы похоже нет. Данное расширение как будто бы начинает скачивание, но тут же завершается "Ошибкой сети".

**Comment by KiberInfinity** [comment]
@gugglegum d62aa969488940efbada41dede3ea315687a399c

**Comment by stamepicmorg** [comment]
@KiberInfinity @gugglegum

Сейчас на хроме, Vkontakte Optimizer 3.0.7 (build 190131), все работает, подтверждаю. Спасибо.

**Comment by dimon4ezzz** [comment]
@KiberInfinity, может, close issue? fix
