### ISSUE TITLE
Не могу найти сохранение переписки

### ISSUE THREAD

**Issue by roman412** [VkOpt/VkOpt#455]
Добрый день,

Подскажите, пожалуйста, функция скачивания переписки была отключена? Не могу найти в интерфейсе.

Если да, то в каком коммите?

Заранее спасибо.

**Comment by KiberInfinity** [comment]
@roman412 
Всё на месте:
![](http://kisshot.ru/imgs/9PIJ79.png)

**Comment by roman412** [comment]
Та не, глобальная. Т.е. все conversations, которые есть. Помню, что была раньше такая функция.

**Comment by KiberInfinity** [comment]
Глобального не было пока что

**Comment by roman412** [comment]
Спасибо. Видимо, я ошибся.

Понимаю, что это вне скоупа данной темы, но можно задать последний вопрос?

Я пока в код сильно не углублялся, но есть ли простой способ как сделать сохранение переписки  без форматирования? Т.е. хочу понять как сохранять весь json что приходит в response после вызова api messages.getHistory().

**Comment by roman412** [comment]
Уже разобрался, можно закрывать.
(Отлавливаю массив msgs на этапе export_messages и засовываю его в JSON.stringify())

**Comment by roman412** [comment]
btw, версия апи, которая используется для запроса сообщений уже была несколько раз обновлена, может стоит и в коде обновить.

**Comment by baitun** [comment]
@arsinclair прошу прощения за беспокойство в давно закрытом треде, но вдруг еще актуально: https://github.com/VkOpt/VkOpt/pull/517
