### ISSUE TITLE
Нет кнопки "скачать" у аудиозаписей в Yandex Browser

### ISSUE THREAD

**Issue by lucky-ly** [VkOpt/VkOpt#458]
Ya.Browser 19.3.1.828
VkOpt 3.0.7.7

В любых списках аудио (страница аудиозаписей, плейлист в шапке, пересланный плейлист в сообщениях) нет кнопки "скачать" у аудиозаписей

**Comment by EgoAkk** [comment]
http://vkopt.net/forum/showthread.php?t=5508
