### ISSUE TITLE
TXT HTML диалоги

### ISSUE THREAD

**Issue by ghost** [VkOpt/VkOpt#466]
последняя версия оперы, последняя версия вашего приложения, пропала опция сохранения диалогов и бесед в TXT. на этом всё. в душе не имею, какие файлы нужно отправлять. гитхабом не пользуюсь. зашел лишь чтобы доложить о проблеме.

**Comment by KiberInfinity** [comment]
89affe2588aacd2416a6cdf62aecb5726d945a9a
Правда теперь скачивает zip архивом с вложенными в него txt-файлами. Один txt на каждую тысячу сообщений в переписке.
