### ISSUE TITLE
Нету кнопки Update в Фоторедакторе

### ISSUE THREAD

**Issue by survivvve** [VkOpt/VkOpt#469]
Пропала кнопка Update. Не могу теперь поменять аватарку без потери лайков и пр.

**Comment by oversmash1** [comment]
Такая же проблема, без понятия, что делать.
Хотелось бы, чтоб проблема решилась..

**Comment by ildartop1** [comment]
у меня тоже пропала

**Comment by KiberInfinity** [comment]
https://github.com/VkOpt/VkOpt/releases/tag/3.0.7.15
