### ISSUE TITLE
Не меняет аву

### ISSUE THREAD

**Issue by markelov666** [VkOpt/VkOpt#471]
Раньше можно было сменить аву с сохранением лайками и комментами. Через Фоторедактор и ниже была секретная кнопка, unload если я не ошибаюсь, сейчас же этой возможности нет...

**Comment by dimon4ezzz** [comment]
@markelov666 вроде как она теперь в `extra` функциях

**Comment by KiberInfinity** [comment]
Исправлено 4c31ea2434cfb42af9ab26889a6761014a456b8b
