### ISSUE TITLE
Не работает скачивание видео

### ISSUE THREAD

**Issue by ForsakenWorld** [VkOpt/VkOpt#475]
Добрый день! Не работает скачивание видео, которое загрузил сам же на свою страницу.
Кнопка скачивания есть (справа, где крестик), при наведении показывает ссылку с надписью "hls".
Но при нажатии на нее просто темнеет экран и ничего больше не происходит даже спустя 5 минут. Грешил на Adblock Plus и NoScript, но даже если их отключить - проблема не уходит.

Вот скриншот кнопки, если нужно (скриншот с записи стрима, поэтому кнопки задублировались).
![изображение](https://user-images.githubusercontent.com/28642811/67634401-77e4a200-f8cc-11e9-9f33-61ed9a3c9aef.png)

URL проблемного видео могу выслать в ответах к этому запросу, если нужно.

Firefox 70.0 x64, VkOpt 3.0.7 (build 190929)

**Comment by KiberInfinity** [comment]
@ForsakenWorld А вк теперь не предоставляет для трансляций (может для всех, может для некоторых) источник видео отличный от hls-плейлиста.
Такие видео можно попробовать скачать через ffmpeg скормив ему ссылку на hls
