### ISSUE TITLE
Ограничение на количество загружаемых фото

### ISSUE THREAD

**Issue by Seeergeeev** [VkOpt/VkOpt#476]
Возможно ли реализовать такой параметр, как количество загружаемых фото из альбома? Например: в альбоме 100 000 фото, а необходимо скачать 5 000 самых свежих. Или скачивать фото загруженые в альбом за определенный период?

**Comment by EgoAkk** [comment]
Возможно всё. Вот только давайте оставим Github для обсуждения технических деталей больше. 
А хотелки и ошибки будем обсуждать на форуме http://vkopt.net/
