### ISSUE TITLE
Не работает новая версия в Chrome Ubuntu

### ISSUE THREAD

**Issue by e1sep0** [VkOpt/VkOpt#477]
https://i.imgur.com/iEJlIfG.png
Вот такая ошибка в режиме разработчика
Спасибо

**Comment by reconn-sp** [comment]
Там проблема в том что stManager._waiters больше нету. Я не разбирался как работает VK и VkOpt, но беглым просмотром решил проблему заменой вот этого (587 строка):
```
stManager && stManager._waiters.push([[key], vk_glue.inj_handler([key])]);
```
на это:
```
stManager && vk_glue.inj_handler(stManager._add(key));
```

Но это ещё не всё, чуть ниже строки 810 для чуть более полного решения проблемы нужно заменить
```
if (wait.length)
               stManager._waiters.push([wait, vk_glue.inj_handler(files)]);
```
на
```
if (wait.length)
                wait.forEach(function (scr) {
                    vk_glue.inj_handler(stManager._add(scr));
                });
```

В результате VkOpt работает, но есть проблемы со стилями при открытии фото, возможно ещё с чем то, но функционал работает, мб завтра, если будет время и не лень, то на работе подробнее изучу, хотя вангую что будет лень 😃

**Comment by nx-x** [comment]
Ну что же, подождем релиза :)

**Comment by reconn-sp** [comment]
Прокачал ещё немного решение, в прошлом скачивание музыки было не доступно, что сильно меня расстроило, потому вот "костыльный фикс №2", строки примерно те же:
 587
```
    StaticFiles[key].isLoading.then(vk_glue.inj_handler([key]))
```
~810
``` 
            if (wait.length) {
                wait.forEach(function (wt) {
                    StaticFiles[wt].isLoading.then(vk_glue.inj_handler([files]))
                });
            }
```

**Comment by journeym** [comment]
После фикса запускается, но конкретно кнопа скачивания аудио не появляется.
Какие-то вещи типп оформления работают.

**Comment by reconn-sp** [comment]
@journeym код брали из последнего комментария? вот у меня прямо сейчас без проблем скачивание работает

**Comment by HanabishiRecca** [comment]
@reconn-sp, хорош, все работает.

![изображение](https://user-images.githubusercontent.com/13597663/69907040-4bea9e00-13ef-11ea-8d9b-7ab16ec18a89.png)

**Comment by journeym** [comment]
> @journeym код брали из последнего комментария? вот у меня прямо сейчас без проблем скачивание работает

Да, только там вообще другие номера строк.
Файл который менял \source\vkopt.js
![image](https://user-images.githubusercontent.com/7759734/69911085-93d4e980-141e-11ea-9e66-c3d0991dc47b.png)
![image](https://user-images.githubusercontent.com/7759734/69911092-a0f1d880-141e-11ea-8ed0-3bed11e3465d.png)

**Comment by journeym** [comment]
Попробовал в последнем релизе билд для хрома, поменять в скрипте vkopt.js
Строки там не такие - 191 и 416.
Не работает точно так же.
Да, и это винда.

**Comment by reconn-sp** [comment]
Эм, мои изменения подходят для того скрипта что в tampermonkey, редактировать надо конечный файл (который устанавливается менеджером скриптов). Насчёт ОС - не важно какая ОС, на работе на маке проделал те же самые изменения и всё так же работает как дома на винде, а линукса у меня уже давно нигде нет.
Так же рекомендую отказаться от установки самого расширения в хроме и хромоподобных браузерах, т.к. в последнее время у меня постоянно возникали какие то проблемы со скриптом, с tampermonkey всё ок + в нём ещё допилил кучу других скриптов, которые не знал куда сунуть но нужны были :-)

**Comment by journeym** [comment]
Ок, я второй коммент пропустил.... :(((((
Все работает

**Comment by reconn-sp** [comment]
обновил первый коммент на всякий 😃

**Comment by nx-x** [comment]
А что, никто не зарелизит ветку с багфиксами? )

**Comment by reconn-sp** [comment]
а смысл релизить костыли? 🤣

**Comment by reconn-sp** [comment]
тут надо нормальный фикс написать, потому что у меня это тупо подбор вызовов по заголовкам методов, минимальный функционал заработал и дальше мне стало лень разбираться 🤣 
З.Ы. я там немного понаблюдал - какой то набор файлов для каких то слушателей плавно растёт со временем, вангую что кончится память на вкладке через неделю-другую непрерывной работы, но пока не вылетело не полезу смотреть 🤣

**Comment by golkov1993** [comment]
В общем есть две версии скрипта по разному написанные и первый скачиваемый отсюда(видимо для Temperonkey) каким-то чудом запустился,а после ваших рекомендательных правок для включения функций скачивания аудио просто перестаёт работать. Да и вообще после этого всего и этот первый обычный скрипт без правок перестал работать. Так же вторая версия( как я понял какой-то правленный кем-то самостоятельно( видно часть из файла vkopt.js) хотя могу и ошибаться в этом, но он тоже не работает если его править вот этими заголовками, но работает если всё вернуть на место. То есть я теперь не могу понять. Либо эти строки не туда ставятся в обоих вариантах скриптов и из-за этого всё ломается или эти заголовки каким-то образом блочит Вконтакте и в результате скрипт не работает. В общем я мало чего могу понимать ибо не знаю основ и принципов работы сайта и скрипта, но хотелось бы прояснить почему происходит так, почему у всех кто здесь отписался скрипт после правок заработал, а у меня нет. Возможно дело во включённом режиме разработчика или ещё что...

**Comment by reconn-sp** [comment]
Просто ты чёт не то делаешь, концепция заключается в том, что Tampermonkey - просто менеджер скриптов, на основании мета данных в начале файла решает нужно ли подключать скрипт (при выполнении перечисленных условий). Действительно есть 2 версии, первая обычное расширение, состоящее из множества файлов и код распределен по назначению или типа того. Формально оба варианта содержат один и тот же код, но упакованный/разложенный по разному, потому строки в расширении могут отличаться от того что я тут написал. Проблема вк в том, что в ВК поменяли загрузчик статических скриптов (файлов) и теперь, как я писал в первом комментарии, один из объектов, используемый для хранения слушателей, во время инициализации не доступен, что приводит к прерыванию запуска. Позже я предложил вариант чтобы не валить ошибку и продолжить загрузку, ещё позже немного более осмысленно доработал и в результате скачивание музыки работает везде, даже в выпадающем меню проигрывателя
![image](https://user-images.githubusercontent.com/18345813/69917801-12f80b00-147b-11ea-861d-d3686d96cef8.png)

В любом случае рекомендую более внимательно прочитать весь тред

**Comment by golkov1993** [comment]
Не не расширение расширением) Я говорил именно про скрипты). Но с ними ладно. Я использовал последний комментарий в хроме в темпманки. То есть я сначала установил скрипт, потом правил его - не заработало. Потом я решил попробовать сразу правленный скрипт, создал его и потом переустановил и даже после этого не сработало. всё как и сказал 587 строка и 810 и ниже.

**Comment by reconn-sp** [comment]
ну а ошибки какие-нибудь вывалились? 😃

**Comment by golkov1993** [comment]
Да две

**Comment by golkov1993** [comment]
Но второй вариант скрипта работает с этими ошибками, хоть и нет скачивания

**Comment by golkov1993** [comment]
Решил проверить эти 2 скрипта путём просмотра кода(что изменится при обновлении/переустановке)
![chrome_ZdwrCg6FRq](https://user-images.githubusercontent.com/13189606/69918152-8c91f800-147f-11ea-9984-fc4c39425647.png)

**Comment by reconn-sp** [comment]
ну так вместо _waiters нужно по другому подписаться

**Comment by golkov1993** [comment]
Ну стМенджера ты сказал нет...

**Comment by golkov1993** [comment]
![image](https://user-images.githubusercontent.com/13189606/69918781-43de3d00-1487-11ea-8667-93fc7585e049.png)
Выполнил проверку синтаксиса

**Comment by journeym** [comment]
Нав скобку забыл там где вставлял в 810.

**Comment by journeym** [comment]
Рабочий скрипт с манки
https://drive.google.com/file/d/1a8ihScWT3zfAWuUzpjhBgtzAGbsfTWQL/view?usp=sharing

**Comment by golkov1993** [comment]
Низкий поклон. Перешерстив код этого понял в чём ошибка. Ну ты её собственно и описал)
И пока пробовал разобраться с исходным понял, что кириллица в описаниях только мешает, сравнив две версии одного и того же кода

**Comment by KiberInfinity** [comment]
8432c06bdcdbbea14ecbdb6d7978f4aa857d07de

**Comment by reconn-sp** [comment]
о, папа пришел, спасибо 😃
