### ISSUE TITLE
Как скачать?

### ISSUE THREAD

**Issue by Zeta-thanos-eagle** [VkOpt/VkOpt#478]
Chrome не даёт установить это расширение, пишет "Chrome Web Store не содержит сведений об этом расширении, то есть оно могло быть установлено без вашего ведома.", MeddleMonkey включает скрипт, но он не работает

**Comment by AHOHNMYC** [comment]
[MeddleMonkey](https://chrome.google.com/webstore/detail/meddlemonkey/moihledlmchhofenpacbhphnbnpakgmo) суть всего лишь форк [ViolentMonkey](https://chrome.google.com/webstore/detail/violentmonkey/jinjaccalgkegednnccohejagnlnfdag), который не обновлялся 3 года.
А так, скрипт сам по себе [пока не работает](https://vkopt.net/forum/showthread.php?p=73549#post73549). #477 #480

**Comment by KiberInfinity** [comment]
Пофикшено 8432c06bdcdbbea14ecbdb6d7978f4aa857d07de
