### ISSUE TITLE
Скачивание переписок

### ISSUE THREAD

**Issue by Apolon4ik** [VkOpt/VkOpt#479]
Здравствуйте, уважаемые разработчики, в последней версии vkopt пропала возможность скачивания переписок, и перехода к началу диалога. Пробовал фаерфокс из магазина и на яндекс браузер через temper monkey, и через распакованное расширение.

**Comment by reconn-sp** [comment]
а сам по себе VKOpt ещё работает? если нет, то прошу сюда https://github.com/VkOpt/VkOpt/issues/477

**Comment by KiberInfinity** [comment]
8432c06bdcdbbea14ecbdb6d7978f4aa857d07de
