### ISSUE TITLE
VkOpt перестал функционировать! :-(

### ISSUE THREAD

**Issue by Maximozavr** [VkOpt/VkOpt#480]
![ошибка VkOpt](https://user-images.githubusercontent.com/7111556/69818666-4eda6880-120e-11ea-9298-3e95f0c6a311.jpg)

**Comment by ForsakenWorld** [comment]
Поддерживаю. VkOpt словно "исчез". При этом расширение включено. Переустановка не помогла.
Mozilla Firefox 70.0.1 64-bit.

**Comment by whatislovees** [comment]
подтверждаю, все также

**Comment by reconn-sp** [comment]
частичное временное решение: https://github.com/VkOpt/VkOpt/issues/477#issuecomment-559363687
восстановлен запуск скрипта и большая часть функционала работает, кривые стили в при просмотре фото остались

**Comment by ForsakenWorld** [comment]
Спасибо) Ждем-с автообновления, ибо вручную пересобирать расширение и ставить... не знаю, как с этим в Firefox. Такое ощущение, что VK специально "вставляет палки в колеса" таким расширениям, как VkOpt.

**Comment by reconn-sp** [comment]
их клюют всякие правообладатели, потому они заинтересованы чтобы таких расширений не было. но ту скорее похоже на оптимизацию работы загрузчика скриптов - зачем то решили переписать

**Comment by KiberInfinity** [comment]
8432c06bdcdbbea14ecbdb6d7978f4aa857d07de
