### ISSUE TITLE
Не работает расширение

### ISSUE THREAD

**Issue by catmurziks** [VkOpt/VkOpt#481]
Все функции исчезли и расширение просто перестало работать в Google Chrome последней версии на момент создания запроса.

**Comment by Sidiusz** [comment]
Подтверждаю, проблема есть

**Comment by whatislovees** [comment]
точно также

**Comment by reconn-sp** [comment]
частичное временное решение: https://github.com/VkOpt/VkOpt/issues/477#issuecomment-559363687
восстановлен запуск скрипта и большая часть функционала работает, кривые стили в при просмотре фото остались

**Comment by Dum4G** [comment]
@reconn-sp заменил точно по инструкции и не работает, где посмотреть в чем косяк?

**Comment by KiberInfinity** [comment]
8432c06bdcdbbea14ecbdb6d7978f4aa857d07de
