### ISSUE TITLE
не работает загрузка музыки в Вк

### ISSUE THREAD

**Issue by Olfla** [VkOpt/VkOpt#484]
не работает загрузка музыки в Вк, Появляется ошибка что установлен еще VKOpt на компьютере, версия хрома 79.0.3945.79

**Comment by KiberInfinity** [comment]
@Olfla Нужно удалить старые версии и оставить только один установленный экземпляр последней версии.

**Comment by ForsakenWorld** [comment]
Установлена последняя (вроде, он сам обновляется) версия VkOpt (build 191215), Firefox 72.0.1 64-bit, не работает скачивание аудио.
Кнопка загрузки есть, но абсолютно все ссылки идут такого вида:
https:// vk .com / undefined # FILENAME / Styles of Beyond - Nine Thou (Grant Mohrman _Superstars_ Remix) .mp3
(как пример, пробелы в URL вставил чтобы ссылка не активна здесь была)
Соответственно, при нажатии на кнопку идет редирект на чью-то страницу с никнеймом undefined в URL.
Не может определить битрейт файла.
На Chrome работает, но криво. Скачивает 15-секундный кусок песни, который приходит в кэш, а в кэш приходят данные с MIME-типом video/MP2T.

Реально ли пофиксить?

**Comment by KiberInfinity** [comment]
@ForsakenWorld проблема актуальна? у меня не получается воспроизвести её.

**Comment by ForsakenWorld** [comment]
@KiberInfinity на данный момент - частично. Заметил следующее:
Некоторые плейлисты ВК отказывается играть - просто skip'ает все треки, словно их не существует. При этом они не заблокированы. В таких плейлистах не работает ни VkOpt, ни другое многим известное расширение для скачивания. Не определяет размер файла даже.
В остальных случаях - работает без проблем.
