### ISSUE TITLE
Обнаружено более одной установленной копии VkOpt`а.

### ISSUE THREAD

**Issue by VlayerRT** [VkOpt/VkOpt#485]
Выдает такую ошибку:
![image](https://user-images.githubusercontent.com/39220694/71447406-1eb7b400-273f-11ea-81dc-71e99f856058.png) ,
но вроде как лишних копий у меня нет. Ставил только через обезьянку
![image](https://user-images.githubusercontent.com/39220694/71447420-51fa4300-273f-11ea-9d12-7cb38c9f7a0b.png)

**Comment by KiberInfinity** [comment]
@VlayerRT 
А что установлено из расширений кроме обезьяны?
Решается ли проблема если отключить ещё и SaveFrom.net?

**Comment by VlayerRT** [comment]
@KiberInfinity 
Проблема решилась сама собой. 
P.S. все расширения в основном у меня отключены до надобности. SF отключал, когда проблема была - не помогало.
