### ISSUE TITLE
Ошибка при сохранении переписки в .txt

### ISSUE THREAD

**Issue by Cornul11** [VkOpt/VkOpt#487]
При попытке сохранить переписку в *.txt, где-то на 23% процесс останвливается и выводится следующая ошибка:
```
vkopt.js:8529 Uncaught TypeError: msg.geo.coordinates.join is not a function
    at make_msg (vkopt.js:8529)
    at part_ready (vkopt.js:8567)
    at vkopt.js:8327
    at onDoneRequest (vk_lib.js:2013)
    at vk_lib.js:2039
    at XMLHttpRequest.AjPost.request.onreadystatechange (vk_lib.js:1280)
```

**Comment by KiberInfinity** [comment]
Исправлено тут:
67c6fadb54b92754e6763774cc01de0a8ad0a15c

**Comment by baitun** [comment]
@KiberInfinity когда этот фикс будет зарелижен?
В Chrome Web Store последняя версия 3.0.7.21, в ней ошибка есть
