### ISSUE TITLE
Проблемы со скачиванием аудио в vk

### ISSUE THREAD

**Issue by DenBogden** [VkOpt/VkOpt#488]
Все аудиозаписи скачиваются пустыми. Не определяется битрейт. невозможно скачать аудиозапись в поиске новостей, приходится добавлять в свои аудиозаписи и скачивать там.

**Comment by pol123qwe** [comment]
Перестало работать скачивание аудио в ВК  ?  То есть  скачиваются файлы  mp3  размером 294 КБ и конечно  не воспроизводятся . Ведь средний развел должен быть примерно 3.5 mb  !  Браузер Гугл хром (Версия 79.0.3945.117 (Официальная сборка), (64 бит) 
![ereмянный](https://user-images.githubusercontent.com/60228328/72997246-1a012100-3e0d-11ea-8ae2-3ca2abd992fb.png)

**Comment by GAnimator** [comment]
Точно такая же проблема, скачивает MP3 весом 291 КБ и не может запустить, что делать, не знаю.
Использую Google Chrome последней версии

**Comment by KiberInfinity** [comment]
@DenBogden @pol123qwe Пофикшено 61ec5edb51f8661687deeba40d2f250e4d3c1d09

**Comment by pol123qwe** [comment]
Круто все работает спс большое ! ! !

**Comment by Neurotoxin001** [comment]
Не работает при скачке со стены, например https://vk.com/wall-36966545_448

скриптовый 3.0.7.20
