### ISSUE TITLE
не скачиваются альбомы

### ISSUE THREAD

**Issue by soredake** [VkOpt/VkOpt#493]
![Screenshot_20200407_134014](https://user-images.githubusercontent.com/5204968/78660184-51904d00-78d5-11ea-95fe-c5493af0f521.png)
[console-export-2020-4-7_13-40-25.txt](https://github.com/VkOpt/VkOpt/files/4443644/console-export-2020-4-7_13-40-25.txt)

**Comment by Zerogoki00** [comment]
Подтверждаю. В консоли такая ошибка
![image](https://user-images.githubusercontent.com/61648511/79571661-3cc96b80-80c4-11ea-80f3-0d2559a5779f.png)

**Comment by KiberInfinity** [comment]
Firefox в последних версиях удалил поддержку используемого у нас API для получения на скачивание файла созданного в indexedDB.

**Comment by KiberInfinity** [comment]
Пока "починил" скачивание 2d88575f3c33b1e53467e355f0366c1caa0a2242
Но RAM съедает теперь больше при выполнении операции.
