### ISSUE TITLE
Опция "Убрать все скругления элементов" не убирает скругление индикатора в историях

### ISSUE THREAD

**Issue by eckff** [VkOpt/VkOpt#498]
Скругление убирается для аватарок, но не для непрочитанного индикатора:
![image](https://user-images.githubusercontent.com/44920739/85294711-a9d3f580-b4a7-11ea-843d-a4b050875385.png)

**Comment by towuk118** [comment]
сог, +

**Comment by KiberInfinity** [comment]
фикс https://github.com/VkOpt/VkOpt/commit/5e5fdf05463dc0aeb5706695d04c16364c36eab4
