### ISSUE TITLE
Не отображаются ссылки на скачку видео и не качает аудио

### ISSUE THREAD

**Issue by Neurotoxin001** [VkOpt/VkOpt#499]
Tampermonkey 4.10
VkOpt 3.0.7.20
Google Chrome 84.0.4147.89

При клике на иконку скачивания аудио:
![image](https://user-images.githubusercontent.com/39812401/87673668-90a82700-c77d-11ea-8404-135caa5571b3.png)

При наведении на иконку скачивания видео:
![image](https://user-images.githubusercontent.com/39812401/87674002-11ffb980-c77e-11ea-9cfb-06cea6600524.png)

Если добавить `mycdn.me` в connect, то ошибки пропадают, но ссылки всё равно не отображаются.

**Comment by Neurotoxin001** [comment]
Разработчики в с ё?

**Comment by Neurotoxin001** [comment]
Проверил на Violentmonkey 2.12.7 – то же самое.

**Comment by Neurotoxin001** [comment]
Разработчики умерли?

**Comment by EgoAkk** [comment]
Просто на гитхабе не ведется обсуждение фич и проблем. Для этого есть форум. 
Гитхаб для обсуждения кода и совместной разработки

**Comment by Neurotoxin001** [comment]
Почему бы тогда не отключить «Issues»?
