### ISSUE TITLE
VkOpt как расширение AdGuard

### ISSUE THREAD

**Issue by Xottab-DUTY** [VkOpt/VkOpt#503]
В AdGuard появилась возможность устанавливать юзер-скрипты. (там они называются расширениями)
К сожалению, VkOpt, установленный таким образом, не работает. (просто никакой реакции)

Было бы хорошо, если бы кто-то посмотрел, в чём там дело..

**Comment by TOWUK** [comment]
не ври ка пожалуйста, все работает!
![image](https://user-images.githubusercontent.com/28830162/94374250-945c1080-0113-11eb-8ca9-2ac5ac1b47e7.png)
![image](https://user-images.githubusercontent.com/28830162/94374257-ad64c180-0113-11eb-9169-013eb20bdec3.png)

**Comment by TOWUK** [comment]
> В AdGuard появилась возможность устанавливать юзер-скрипты. (там они называются расширениями)
> К сожалению, VkOpt, установленный таким образом, не работает. (просто никакой реакции)
> 
> Было бы хорошо, если бы кто-то посмотрел, в чём там дело..

единственное что отвал половины апи вк пошел, да согласен пора бы и обновить в вк опт, я вручную обновил версибю вк апи скрипта но ничего не помогло

**Comment by Xottab-DUTY** [comment]
Ну, если бы я врал, я бы не создавал эту тему =)

Как расширение AdGuard ВкОпт у меня не работает, а как обычное расширение для браузера (установленное в режиме разработчика) – работает.

**Comment by TOWUK** [comment]
> Ну, если бы я врал, я бы не создавал эту тему =)
> 
> Как расширение AdGuard ВкОпт у меня не работает, а как обычное расширение для браузера (установленное в режиме разработчика) – работает.

установи так:
![image](https://user-images.githubusercontent.com/28830162/94374353-65926a00-0114-11eb-9789-a643aa1b906d.png)
![image](https://user-images.githubusercontent.com/28830162/94374356-6fb46880-0114-11eb-971f-892a00f9e109.png)
![image](https://user-images.githubusercontent.com/28830162/94374362-76db7680-0114-11eb-9abc-4f90d997f422.png)

**Comment by Xottab-DUTY** [comment]
Так не работает. Файл просто скачивается браузером.

**Comment by TOWUK** [comment]
> Так не работает. Файл просто скачивается браузером.

у тя установлен нормально адгард, лицуха?

**Comment by Xottab-DUTY** [comment]
Да. Релиз.

**Comment by TOWUK** [comment]
> Да. Релиз.

Сделай так:
![image](https://user-images.githubusercontent.com/28830162/94374572-ea31b800-0115-11eb-9f75-67b6695b97dd.png)
![image](https://user-images.githubusercontent.com/28830162/94374584-ffa6e200-0115-11eb-9486-715e3e1952d1.png)

**Comment by Xottab-DUTY** [comment]
...
Спасибо, но не нужно меня учить устанавливать. Я именно так и устанавливал.

**Comment by EgoAkk** [comment]
Предложения по новым функциям лучше оставлять в соответствующей теме на форуме http://vkopt.net/forum/showthread.php?t=5
