### ISSUE TITLE
[Предложение] Опция переименования "Мессенджера"

### ISSUE THREAD

**Issue by TheZBlock** [VkOpt/VkOpt#504]
Там переименовали "Сообщения" в "Мессенджер", видимо, чтобы исправить тот косяк с двумя пунктами, начинающимися на "СООБЩЕ", который получился после переименования "Групп" в "Сообщества".

Так вот: было бы неплохо заполучить опцию переименования "Мессенджера" в "Сообщения" обратно.

**Comment by EgoAkk** [comment]
Запросы на новые функции и ошибки обсуждаются на форуме.
Там уже есть запрос на такую функцию. Спасибо
