### ISSUE TITLE
Возможность заменить "Мессенджер" на "Сообщения"

### ISSUE THREAD

**Issue by raitonoberu** [VkOpt/VkOpt#505]
Спасибо за VkOpt, он потрясающе исправляет все косяки соц. сети.
Недавно они испортили ещё одну вещь - заменили ласкающую глаз надпись "Сообщения" на ущербную "Мессенджер". хотя от мессенджера там ровным счётом ничего.
Вы сделали возможным замену текста вкладки сообществ на "Группы", не могли бы сделать то же самое с сообщениями?

**Comment by 1323ED5** [comment]
Можно использовать для этого моё расширение, оно позволяет переименовывать вообще все разделы
https://github.com/1323ED5/VK_renaming_tool/
![image](https://user-images.githubusercontent.com/50923055/103096084-92c3bb00-4624-11eb-8c57-93d49a54a673.png)

**Comment by EgoAkk** [comment]
Предложения по новым функциям лучше оставлять в соответствующей теме на форуме http://vkopt.net/forum/showthread.php?t=5
