### ISSUE TITLE
Перестало скачиваться аудио

### ISSUE THREAD

**Issue by TaciturnShadow** [VkOpt/VkOpt#507]
Перестало скачиваться аудио, вместо скачивания открывается ссылка
https://vk.com/undefined#FILENAME/<название>.mp3

**Comment by BaHeK1994** [comment]
```
var o = {
    v: function (e) {
        return e.split('').reverse().join('')
    },
    r: function (e, t) {
        var n;
        e = e.split('');
        for (var o = r + r, i = e.length; i--;) ~(n = o.indexOf(e[i])) && (e[i] = o.substr(n - t, 1));
        return e.join('')
    },
    s: function (e, t) {
        var n = e.length;
        if (n) {
            var r = function (e, t) {
                    var n = e.length,
                        r = [];
                    if (n) {
                        var o = n;
                        for (t = Math.abs(t); o--;) t = (n * (o + 1) ^ t + o) % n,
                            r[o] = t
                    }
                    return r
                }(e, t),
                o = 0;
            for (e = e.split(''); ++o < n;) e[o] = e.splice(r[n - 1 - o], 1, e[o]) [0];
            e = e.join('')
        }
        return e
    },
    i: function (e, t) {
        return o.s(e, t ^ vk.id)
    },
    x: function (e, t) {
        var n = [];
        return t = t.charCodeAt(0),
            each(e.split(''), (function (e, r) {
                n.push(String.fromCharCode(r.charCodeAt(0) ^ t))
            })),
            n.join('')
    }
};

function a(e) {
    var r = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMN0PQRSTUVWXYZO123456789+/=';
    if (!e || e.length % 4 == 1) return !1;
    for (var t, n, o = 0, i = 0, a = ''; n = e.charAt(i++);) ~(n = r.indexOf(n)) && (t = o % 4 ? 64 * t + n : n, o++ % 4) && (a += String.fromCharCode(255 & t >> (-2 * o & 6)));
    return a
}

function mp3_to_m3u8(e) {
    if (~e.indexOf('audio_api_unavailable')) {
        var t,
            n,
            r = e.split('?extra=')[1].split('#'),
            i = '' === r[1] ? '' : a(r[1]);
        if (r = a(r[0]), 'string' != typeof i || !r) return e;
        for (var s = (i = i ? i.split(String.fromCharCode(9)) : []).length; s--;) {
            if (t = (n = i[s].split(String.fromCharCode(11))).splice(0, 1, r) [0], !o[t]) return e;
            r = o[t].apply(null, n)
        }
        if (r && 'http' === r.substr(0, 4)) return r
    }
    return e
}
```

выдернул из min.js VK, функция превращает audio_api_unavailable.mp3 в .m3u8
получение ссылки:
`console.log(mp3_to_m3u8('https://vk.com/mp3/audio_api_unavailable.mp3?extra=yZDqv2vZB3ftANrVswD2ugXTBMrZsNqTmNjgzgrcAMvXzK5zog44rKHerOj5ywTWs1jFCg50s1P0zwL5vMvRDhyVus9vrgrFBeOTuKf2lIy9qKP2DMjhAtDOntjLsJeVzuvWmdbysw42yvH4otK/qMS5mxHkBMm4lJvIndPsvhjbANLLDxzSC3uXzw85nhDqve9UAve1CJqWzNqZy1jZAwHUs2yVtMjnBMfPvhvFmJHZDOHUy1LnwxD0v2PTn3m4COHHyZLXmxuZs3HXlZG5BfDTm2L0uJHhnJmZnZO5sdK2EuLNEMrjzsOYlJfPAY9Vy2f6Aq#AqSXmJm'));`
Результат:
`https://cs1-52v4.vkuseraudio.net/p7/86a597e891/e7b93dc4b6910e/index.m3u8?extra=f0IiWIzvnvMWs_dGHheiPBFkKRjjJW8oaNy28E2mQnYcptiH-JU9q7XiPgM_fSY0zRewA5RqRvIMb9JHH63PD9h3GwoG9BkARsNBifayswlvjnKZX-8Blih2cKTIQjnyyV1q3ODxqm8nFKYcJdls4TTr&long_chunk=1`

PS: как все это работает, я не знаю. Просто скопировал то, что нашел в коде, чтобы это заработало, ну а .m3u8 VKOpt уже умеет скачивать

**Comment by BaHeK1994** [comment]
закинул пулл реквест: https://github.com/VkOpt/VkOpt/pull/508

**Comment by TaciturnShadow** [comment]
Спасибо, всё работает.

**Comment by yuhrim** [comment]
> Спасибо, всё работает.

Подскажите, пожалуйста, чайнику, что делать с этой инфой?) Можно пошаговую инструкцию, если не сложно?

**Comment by BaHeK1994** [comment]
> > Спасибо, всё работает.
> 
> Подскажите, пожалуйста, чайнику, что делать с этой инфой?) Можно пошаговую инструкцию, если не сложно?

1) отключить расширение vkopt
2) установить [Tampermonkey](https://www.tampermonkey.net/)
3) открыть эту ссылку: https://github.com/BaHeK1994/VkOpt/blob/master/builds/vkopt_script.user.js?raw=true
Tampermonkey сам предложит установить скрипт
4) когда выйдет официальный релиз (окошко о том, что версия обновлена), тогда можно бдует все вернуть обратно

**Comment by yuhrim** [comment]
>    Tampermonkey сам предложит установить скрипт
Спасибо, всё работает!

**Comment by yuhrim** [comment]
>    Tampermonkey сам предложит установить скрипт

Спасибо, всё работает!

**Comment by RhaegarTargaryen55** [comment]
Пару дней поработало, а потом перестало. Скачивает файлы по 170 килобайт. Может кто знает как починить?

> > > Спасибо, всё работает.
> > 
> > 
> > Подскажите, пожалуйста, чайнику, что делать с этой инфой?) Можно пошаговую инструкцию, если не сложно?
> 
> 1. отключить расширение vkopt
> 2. установить [Tampermonkey](https://www.tampermonkey.net/)
> 3. открыть эту ссылку: https://github.com/BaHeK1994/VkOpt/blob/master/builds/vkopt_script.user.js?raw=true
>    Tampermonkey сам предложит установить скрипт
> 4. когда выйдет официальный релиз (окошко о том, что версия обновлена), тогда можно бдует все вернуть обратно

**Comment by BaHeK1994** [comment]
> Пару дней поработало, а потом перестало. Скачивает файлы по 170 килобайт. Может кто знает как починить?
> 
> > > > Спасибо, всё работает.
> > > 
> > > 
> > > Подскажите, пожалуйста, чайнику, что делать с этой инфой?) Можно пошаговую инструкцию, если не сложно?
> > 
> > 
> > 
> > 1. отключить расширение vkopt
> > 2. установить [Tampermonkey](https://www.tampermonkey.net/)
> > 3. открыть эту ссылку: https://github.com/BaHeK1994/VkOpt/blob/master/builds/vkopt_script.user.js?raw=true
> >    Tampermonkey сам предложит установить скрипт
> > 4. когда выйдет официальный релиз (окошко о том, что версия обновлена), тогда можно бдует все вернуть обратно

Отключите все другие скрпиты, которые скачивают аудио.

**Comment by KiberInfinity** [comment]
https://github.com/VkOpt/VkOpt/commit/076150604182faf542d3be7cc9a90013c444070a
фикс скачивания

**Comment by RhaegarTargaryen55** [comment]
спасибо конечно, но что с этим нужно делать? vkopt установлен в Tampermonkey

> [0761506](https://github.com/VkOpt/VkOpt/commit/076150604182faf542d3be7cc9a90013c444070a)
> фикс скачивания

**Comment by KiberInfinity** [comment]
@RhaegarTargaryen55 
Пока что можно собрать и использовать как расширение в режиме разработчика
https://vk.com/vkopt_club?w=page-16925304_54429056

**Comment by RhaegarTargaryen55** [comment]
начал делать и хотел спросить, чем открыть _build.sh на маке? что бы этот скрипт выполнился

> @RhaegarTargaryen55
> Пока что можно собрать и использовать как расширение в режиме разработчика
> https://vk.com/vkopt_club?w=page-16925304_54429056

**Comment by KiberInfinity** [comment]
@RhaegarTargaryen55  из терминала выполнить 
```
./_build.sh
```

**Comment by RhaegarTargaryen55** [comment]
@KiberInfinity получилось, спасибо

**Comment by Neurotoxin001** [comment]
Проблема всё еще на месте при использовании скрипта по ссылке из релизов
