### ISSUE TITLE
Yandex поиск фото

### ISSUE THREAD

**Issue by Seven0n** [VkOpt/VkOpt#509]
Незначительно, но при нажатии поиска фото в яндексе теперь просто выдает страничку яндекс и приходится из ссылки копировать URL изображения и вставлять в поиск.

**Comment by KiberInfinity** [comment]
Тут был фикс
https://github.com/VkOpt/VkOpt/commit/20491382852af1c354afe8aa7c6444ecabe6804a
Но да, всё ещё не в релизе
