### ISSUE TITLE
Подписанное расширение для FireFox

### ISSUE THREAD

**Issue by wasiliysoft** [VkOpt/VkOpt#512]
Есть ли смысл ждать подписанный вариант расширения для установки в FireFox? 
Версию из исходников получается установить только с отключением проверки подписи (в корпоративной версии браузера или версии для разработчиков) либо как временное расширение которое удаляется при перезапуске браузера.

**Comment by EgoAkk** [comment]
Такие вопросы лучше обсуждать на форуме проекта. 
Смысл ждать есть. Как только будет готов набор исправлений - будет выпущена новая версия расширения и у всех автоматически обновится подписанная версия.
