### ISSUE TITLE
Ошибка при выгрузке истории чата

### ISSUE THREAD

**Issue by PhantomArt** [VkOpt/VkOpt#514]
Пытаюсь сохранить историю чата, переписки там очень много. Судя по консоли выгружает исправно в течении долгого времени. Но каждый раз на 39.44% операция замирает. В консоли в этот момент падает ошибка Uncaught TypeError: msg.geo.coordinates.join is not a function.

Можно ли это исправить или хотя бы временно обойти?

**Comment by PhantomArt** [comment]
Закомментировал временно строки:

```               if (msg.geo)
                  attach_text += (msg.geo['place'] || {'title':'---'})['title'] + ': https://www.google.com/maps/@'+msg.geo['coordinates'].join(',');```

Это помогло.

**Comment by EgoAkk** [comment]
Спасибо за информацию. Но сообщения об ошибках лучше оставлять на форуме в соответствующей теме: http://vkopt.net/forum/showthread.php?t=6
