### ISSUE TITLE
[Предложение] Сохранение всех диалогов на аккаунте

### ISSUE THREAD

**Issue by ivekarp** [VkOpt/VkOpt#516]
Я конечно извиняюсь, что пишу не на форуме, но зарегистрировался там, а создать тему почему-то так и не получилось.
Вот что я предлагаю сделать (по крайней мере, такой функции я не нашёл в расширении) - функцию сохранения всех переписок на аккаунте в файлы html

**Comment by EgoAkk** [comment]
Предложения по новым функциональностям можно оставить в этой теме форума: http://vkopt.net/forum/showthread.php?t=5
